### ISSUE TITLE
PoseWithCovarianceStampedがうまく表示されない

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_recognition#1045]
#1041 のPRを使ってPoseWithCovarianceStampedを表示しようとしているのですが、対角成分が大きくなると表示すべきpointcloudの領域が増えてしまい、重くなりうまく表示ができません。

**Comment by garaemon** [comment]
rqt_reconfigureで点群の解像度が設定できるので変えてみてください

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros#parameters-31

**Comment by h-kamada** [comment]
* 対角成分を0.3とした場合

![0 3](https://cloud.githubusercontent.com/assets/7262021/9199192/0e2ac0a4-407c-11e5-89d6-a7f8e944683e.png)

* 対角成分を1とした場合

![1](https://cloud.githubusercontent.com/assets/7262021/9199193/0fb4a4b2-407c-11e5-98a6-df277d685c5f.png)

* 対角成分を3とした場合

![3](https://cloud.githubusercontent.com/assets/7262021/9199197/1199b358-407c-11e5-8b2b-f1c462379569.png)

**Comment by h-kamada** [comment]
このような表示になるのですが、感覚的に対角成分を増加させるとむしろ領域が狭まっていきそうな気がするのですが、勘違いでしょうか？

**Comment by garaemon** [comment]
https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Normal_Distribution_PDF.svg

sigmaが大きい方が分布がだらだらと広くなるんじゃない?

**Comment by garaemon** [comment]
`sigma^2=3`だと3sigmaまで表示するプログラムなので、`sqrt(3) * 3 = 5.19`なので+-5m程度の描画になるように作った気がします

**Comment by h-kamada** [comment]
あ、勘違いですすみません。
adaptive kalmanfilterを導入してみると、対角成分が68くらいの時にこれくらいのスケールです
![screenshot_from_2015-08-11 23 16 34](https://cloud.githubusercontent.com/assets/7262021/9199728/0a0e3c78-407f-11e5-83ee-b94a8444724b.png)

**Comment by garaemon** [comment]
単位がmmだったりはしない?

**Comment by h-kamada** [comment]
単位mmでした。
mに直してしまうと今度は小さくなりすぎてしまうので、自分のコードのどこかがまだおかしいかもしれません、、

**Comment by garaemon** [comment]
逆にresolutionを小さくしてみると可視化できるかも。これもsigmaの大きさに依存させて決定した方がよさそうだね。もしくはサンプリングの個数を固定にした方がいいか

2015年8月11日火曜日、h-kamada<notifications@github.com>さんは書きました:

> Closed #1045 <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1045>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1045#event-379234985>
> .
>


-- 
✉︎ from iPhone

**Comment by garaemon** [comment]
分散の値は正しそうなのかな？
やりたいこととしては、実はKFなんか使わなくても単純に直近のデータ列から分散を計算してみればいいだけな気はしてきた

2015年8月11日火曜日、Ryohei Ueda<garaemon@gmail.com>さんは書きました:

>
> 逆にresolutionを小さくしてみると可視化できるかも。これもsigmaの大きさに依存させて決定した方がよさそうだね。もしくはサンプリングの個数を固定にした方がいいか
>
> 2015年8月11日火曜日、h-kamada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> Closed #1045 <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1045>
>> .
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1045#event-379234985>
>> .
>>
>
>
> --
> ✉︎ from iPhone
>


-- 
✉︎ from iPhone

**Comment by k-okada** [comment]
KFかParticleFilterかは別にして現在の対象の市姿勢を推定するのにはやはりトラッキングは必要かと．

--
◉ Kei Okada


2015-08-11 23:51 GMT+09:00 Ryohei Ueda <notifications@github.com>:
