### ISSUE TITLE
Why jsk_pcl/* on README in jsk_perception?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1165]
@garaemon 

https://github.com/jsk-ros-pkg/jsk_recognition/tree/6a83868c95fe2d35fa84e10cbf398e911b7bdd9b/jsk_perception#jsk_pcltabletopcolordifferencelikelihood

And the image is from jsk_pcl_ros/images/ .
That's confusing to me.

Because of that, there is some dead link in new readthedocs documents.
http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/nodes/colorize_float_image.html

**Comment by garaemon** [comment]
it's just a mistake.

**Comment by wkentaro** [comment]
Ok.
