### ISSUE TITLE
[checkerboard_detector]  different pose b/w PoingCloud and Detected Pose

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1181]
![image](https://cloud.githubusercontent.com/assets/4310419/10117599/df59960c-6497-11e5-8d9e-044d655f7a81.png)
![image](https://cloud.githubusercontent.com/assets/4310419/10117603/fedc77ce-6497-11e5-9b9e-cef0df9e9849.png)

There is difference between PoseStamped (which is published by checkerboard_detector) and PointCloud when visualize.

Am I missing something?

I'm using checkerboard
* board_type: chess
* grid_size: 6 x 5
* rect_size: 0.03 x 0.03

**Comment by garaemon** [comment]
Is camera intrinsic parameter calibrated?

**Comment by wkentaro** [comment]
Not so much, maybe that is the cause.

**Comment by garaemon** [comment]
check debug image and confirm checkerboard is detected correctly first.
If it is correct, you are using size of checkerboard or intrinsic camera parameter.

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/10117664/c2f7a326-6499-11e5-8602-f858f8d0b01e.png)

checkerboard seems detected correctly.
I will do calibration of kinect2.

**Comment by garaemon** [comment]
Looks good, intrinsic parameter and checkerboard size may be wrong.

**Comment by wkentaro** [comment]
is checkerboard size also wrong?
that size is written on the board.

**Comment by garaemon** [comment]
> that size is written on the board.

measure it and 1mm difference of checkerboard size will result in 1cm error of estimated checkeboard pose.

**Comment by wkentaro** [comment]
I see, I will.

2015年9月26日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> that size is written on the board.
>
> measure it and 1mm difference of checkerboard size will result in 1cm
> error of estimated checkeboard pose.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1181#issuecomment-143441432>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
The checkerboard was printed with reduction of scale, so the actual rectsize was 0.0278 not 0.03.
After changing the specified size, the distance looks correct but pointcloud does not.
https://drive.google.com/open?id=0B9P1L--7Wd2vTWc2dnJfcnlUTzQ

And I calibrated kinect2 on baxter head, and it now looks better.
https://drive.google.com/open?id=0B9P1L--7Wd2vZUxGSXFiaHppSFE

Thank you.
