### ISSUE TITLE
[jsk_pcl_ros] ClusterPointIndicesDecomposer does not publish clouds

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1187]
![image](https://cloud.githubusercontent.com/assets/4310419/10252797/c038f998-6974-11e5-8a1d-777587e282e6.png)

I used the launch file in jsk_pcl_ros/launch.
but actually there is no clouds.

The launch file I used was below (edited some lines):
https://github.com/wkentaro/jsk_recognition/blob/cluster-pi-trial/jsk_pcl_ros/launch/euclidean_segmentation.launch

**Comment by garaemon** [comment]
try ClusterPointIndicesDecomposer instead of ClusterPointIndicesDecomposerZAxis

**Comment by wkentaro** [comment]
I also tried it, but seems not publish clouds.
and It seems that the feature is not used recently.

**Comment by garaemon** [comment]
check timestamp of inputs of cluster decomposer

**Comment by garaemon** [comment]
/pcl_nodelet/voxelgrid/output and /pcl_nodelet/clustering/output

**Comment by wkentaro** [comment]
I found the reason, ClusterPointIndices does not prepare publications before subscribing cluster_point_indices because number of clusters is unknown.
That is the reason why there is no clouds topics in rostopic list because ConnectedBasedNodelet does not subscribe topics until subscribed.

**Comment by wkentaro** [comment]
I can see clouds after subscribing one of the topics.

**Comment by garaemon** [comment]
I see, tricky. Please use debug_output (http://jsk-recognition.readthedocs.org/en/latest/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.html#publishing-topics)

I don't recomment to use `~output%02d` topics

**Comment by wkentaro** [comment]
BTW, are there simple command line tool to apply point indices to point
cloud?

I'd like to use it when viewing on rviz.

2015年10月3日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> I see, tricky. Please use debug_output (
> http://jsk-recognition.readthedocs.org/en/latest/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.html#publishing-topics
> )
>
> I don't recomment to use ~output%02d topics
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1187#issuecomment-145098339>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
pcl_msgs/PointIndices? You can use pcl/ExtractIndices

**Comment by wkentaro** [comment]
Not for writing code but command line tool.
Like:

rosrun jsk_pcl_ros pointindices_to_pointcloud ~input:=/kinect2/qhd/points
~target:=/pointcloudindices

2015年10月3日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> pcl_msgs/PointIndices? You can use pcl/ExtractIndices
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1187#issuecomment-145129412>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com
