### ISSUE TITLE
[jsk_pcl_ros] AttentionClipper dies unexpectedly when subscribe its topic

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1188]
![image](https://cloud.githubusercontent.com/assets/4310419/10254559/81c150e2-697f-11e5-8597-88502f6f167e.png)

There are no error..

**Comment by garaemon** [comment]
Your tf looks illegal

**Comment by wkentaro** [comment]
I think I transform the tf correctly.

https://github.com/wkentaro/jsk_apc/blob/filter-pod-outer/jsk_2015_apc_common/launch/in_kiva_pod_clipper.launch

And without any change of code, it is now fixed.. I don't know the reason..

**Comment by garaemon** [comment]
Do you use `rosbag play -l`?

**Comment by wkentaro** [comment]
At present?
No I'm using the realtime data in lab.

**Comment by wkentaro** [comment]
In fact, I doubt the change of jsk_topic_tools/ConnectedBasedNodelet. because nodelet_manager dies in this issue.

**Comment by wkentaro** [comment]
And I'm doing `git checkout` and `catkin bt` recursively...

**Comment by garaemon** [comment]
hmm, please test with gdb.

**Comment by wkentaro** [comment]
> hmm, please test with gdb.

Actually, I don't have the error at present. I don't know why as said above..
I will do the test when I encountered same problem.

**Comment by wkentaro** [comment]
I think I found the reason.
AttentionClipper dies when negative value is specified as initial_pos_(x|y|z).
I don't know where is the cause of this at present.

**Comment by wkentaro** [comment]
these lines may be the cause.
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_topic_tools/src/rosparam_utils.cpp#L48-L55

```
throw std::runtime_error("the value cannot be converted into double")
```

does not appear the screen of roslaunch.

**Comment by garaemon** [comment]
`XmlRpc::XmlRpcValue::TypeDouble` cannot catch negative values?

**Comment by wkentaro** [comment]
Yeah I doubt that.

**Comment by wkentaro** [comment]
I don't know how to do print debug in that file (rosparam_utils.cpp) because ROS_WARN does not appear..

**Comment by garaemon** [comment]
> I don't know how to do print debug in that file (rosparam_utils.cpp) because ROS_WARN does not appear..

really? it's strange but please use `std::cerr` as quick hack.

**Comment by wkentaro** [comment]
I confirmed that  `XmlRpc::XmlRpcValue::TypeDouble` does not catch negative value.

**no negative**
![image](https://cloud.githubusercontent.com/assets/4310419/10261495/80947ab8-69d5-11e5-806e-61fa0de00aeb.png)


**with negative**
![image](https://cloud.githubusercontent.com/assets/4310419/10261488/6375d8aa-69d5-11e5-8ac3-cafb0b5dcc06.png)


You can focus on `jsk_topic_tools 8` message.

**Comment by wkentaro** [comment]
Actually I'm not familiar to C++ libraries.
Do you know some alternatives or how to fix this?

**Comment by garaemon** [comment]
can you show me `rosparam get` result?

**Comment by wkentaro** [comment]
dimension_x: 0.25
dimension_y: 0.22
dimension_z: 0.22
frame_id: /kiva_pod_base
initial_pos: [-.21, 0.29, 0.36]
initial_rot: [0, 0, 0]

​

On Sat, Oct 3, 2015 at 2:04 PM, Ryohei Ueda <notifications@github.com>
wrote:

> can you show me rosparam get result?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1188#issuecomment-145200903>
> .
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
> initial_pos: [-.21, 0.29, 0.36]

-0.21? Do you have 0 in your launch file?

**Comment by wkentaro** [comment]
oh, -.21 does not work for Xml:Rpc.
It is fixed.
Sorry, I thought this can be used (becausee python allow)..

**Comment by wkentaro** [comment]
Xml:Rpc allows .29 but not -.29.

**Comment by garaemon** [comment]
regular expression should be `^[+-]?(\d*\.\d+|\d+\.?\d*)([eE][+-]?\d+|)` but libxml is probably wrongly implemented.

**Comment by wkentaro** [comment]
I see.
Should we warn about it in this?
https://github.com/jsk-ros-pkg/jsk_common/pull/1157

**Comment by garaemon** [comment]
> Should we warn about it in this?

Yes, it should help users a lot

**Comment by garaemon** [comment]
> jsk-ros-pkg/jsk_common#1157

I've commented about improvements.

**Comment by wkentaro** [comment]
Closed via https://github.com/jsk-ros-pkg/jsk_common/pull/1157
