### ISSUE TITLE
split location of scripts and nodes

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1239]
I think scripts and nodes should be located in different directories.

I mean as 
**scripts** for example:

*  https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/download_trained_data.sh
* https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/check_cascadeclassifier.py

and 
**nodes** for example:

* https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/image_publisher.py
* https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/label_image_decomposer.py

do you have any idea? @garaemon 

One option is to move **scripts** to `bin` dir under each package root dir.

**Comment by garaemon** [comment]
node_scripts directory?

**Comment by wkentaro** [comment]
+1

**Comment by garaemon** [comment]
change  as you like. :relaxed:

**Comment by wkentaro** [comment]
thanks. :sunglasses:
