### ISSUE TITLE
[question] [jsk_perception] Is that possible to merge two images from two Kinects?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1262]
as #1261 to point clouds.

**Comment by garaemon** [comment]
tile_image?

meging image is difficult because simply merged image does not satisfy
camera model.
if you put the third virtual camera at the middle of them, you can create
image from pointcloud not from images.
i don't know virtual_camera_publisher supprts it.


2015年10月19日月曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> as #1261 <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1261> to
> point clouds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1262>.
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
Thank you for your information.
I will search on google for that.

2015年10月19日月曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> tile_image?
>
> meging image is difficult because simply merged image does not satisfy
> camera model.
> if you put the third virtual camera at the middle of them, you can create
> image from pointcloud not from images.
> i don't know virtual_camera_publisher supprts it.
>
>
> 2015年10月19日月曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > as #1261 <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1261> to
> > point clouds.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1262>.
> >
>
>
> --
> ✉︎ from iPhone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1262#issuecomment-149226566>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
If you need to implement it, [this](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/add_color_from_image_nodelet.cpp#L107) is a good sample.

But if you want to implement it in realtime, you may need to use GPU to render pointcloud on image.
keywords: depth buffer, z buffer, offscreen rendering, OpenGL

**Comment by garaemon** [comment]
references
* http://research.microsoft.com/en-us/um/redmond/projects/hyperlapse/
* http://repository.dl.itc.u-tokyo.ac.jp/dspace/bitstream/2261/43684/1/48037413.pdf

**Comment by garaemon** [comment]
* [DepthImageCreator](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/depth_image_creator_nodelet.cpp) can generate depth image from point cloud.

**Comment by wkentaro** [comment]
Thanks.
I have tried `convert_pointcloud_to_image` and it does not work on my issue.
http://wiki.ros.org/pcl_ros

I'd like to try implement these feature, but I don't have time for it now.
Maybe I will try in the future.
