### ISSUE TITLE
multisense_ros driver publish 8UC1 and this causes error in cv_bridge of jsk multisense pipline 

### ISSUE THREAD

**Issue by orikuma** [jsk-ros-pkg/jsk_recognition#1266]
We can avoid this problem by `roscd multisense_ros && hg up 3.4.3`.
ref. https://bitbucket.org/crl/multisense_ros/issues/52/image_rect-has-8uc1-format-not-mono8

**Comment by garaemon** [comment]
will be fixed soon

**Comment by garaemon** [comment]
https://bitbucket.org/crl/multisense_ros/issues/52/image_rect-has-8uc1-format-not-mono8
fixed
