### ISSUE TITLE
[bug] [jsk_recognition_utils] Opposite transformation in lookupTransformWithDuration()

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1269]
current
```
listener->lookupTransform(
  from_frame, to_frame, stamp, transform);
```

**correctly**

```
listener->lookupTransform(
  /*target_frame=*/to_frame, /*source_frame=*/from_frame, /*time=*/stamp, /*transform=*/transform);
```

http://docs.ros.org/jade/api/tf/html/c++/classtf_1_1Transformer.html#ac01a9f8709a828c427f1a5faa0ced42b

**Comment by wkentaro** [comment]
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/1271#issuecomment-149628708 for *before* and *after*.

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/include/jsk_recognition_utils/tf_listener_singleton.h#L58

```
  tf::StampedTransform lookupTransformWithDuration(
    tf::TransformListener* listener,
    const std::string& to_frame,
    const std::string& from_frame,
    const ros::Time& stamp,
    ros::Duration duration);
```

**Comment by garaemon** [comment]
current implementation is correct and lookupTransformWithDuration is already used in some nodelets.
If you want to swap to_fram and from_frame, 
1. rename argument
2. fix cpp implementation
3. fix all lookupTransformWithDuration used

**Comment by wkentaro** [comment]
> current implementation is correct

I don't think so. See:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/src/tf_listener_singleton.cpp#L69-L70

**Comment by wkentaro** [comment]
>  lookupTransformWithDuration is already used in some nodelets.

Yeah, so maybe we need test all nodes. :sob:

**Comment by garaemon** [comment]
Hmm, I'm not confident about this issue...

**Comment by garaemon** [comment]
Start with writing unittest in jsk_recognition_utils.

**Comment by wkentaro** [comment]
It's simple, isn't it? from_frame and to_frame should be passed to opposite pos.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/src/tf_listener_singleton.cpp#L69-L70

because from_frame is source_frame, and to_frame is target_frame.

**Comment by garaemon** [comment]
```
$ rosrun tf tf_echo
Usage: tf_echo source_frame target_frame

This will echo the transform from the coordinate frame of the source_frame
to the coordinate frame of the target_frame. 
Note: This is the transform to get data from target_frame into the source_frame.
```

But it uses in opposite manner.
https://github.com/ros/geometry/blob/indigo-devel/tf/src/tf_echo.cpp#L107
```
        echoListener.tf.lookupTransform(source_frameid, target_frameid, ros::Time(), echo_transform);
```

But tf document says
```
void Transformer::lookupTransform	(	const std::string & 	target_frame,
const std::string & 	source_frame,
const ros::Time & 	time,
StampedTransform & 	transform 
)		const
```

is tf document wrong?

**Comment by garaemon** [comment]
https://github.com/ros/geometry/issues/108
reported

**Comment by garaemon** [comment]
I think order of arguments of `tf::Transformer::lookupTransformation` will not change because it will affect so many codes.

we need to write unittest to be confident about tf.
1. run `static_tf_transform_publisher` with known offset
2. verify the offset by `TfLookupTransformWithDuration`

**Comment by wkentaro** [comment]
Ok, TfLookupTransformWithDuration is just a shallow wrapper of
tf::lookupTransform, so I will write a test for it and will change
TfLookupTransformWithDuration according to the result.


2015年10月22日木曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> I think order of arguments of tf::Transformer::lookupTransformation will
> not change because it will affect so many codes.
>
> we need to write unittest to be confident about tf.
> 1. run static_tf_transform_publisher with known offset
> 2. verify the offset by TfLookupTransformWithDuration
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1269#issuecomment-150173390>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
I sent PR to test tf::Transform::lookupTrasform: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1274

**Comment by wkentaro** [comment]
closes via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1324
