### ISSUE TITLE
Segfault SLICSuperPixels because of large image

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1308]
https://gist.github.com/wkentaro/84e4cd9ee84a206cef3e

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef179700 (LWP 12514)]
[New Thread 0x7fffee978700 (LWP 12515)]
[New Thread 0x7fffee177700 (LWP 12516)]
[New Thread 0x7fffed976700 (LWP 12517)]
[New Thread 0x7fffed175700 (LWP 12518)]
[New Thread 0x7fffec974700 (LWP 12519)]
[New Thread 0x7fffe7fff700 (LWP 12521)]
[New Thread 0x7fffe77fe700 (LWP 12522)]
[New Thread 0x7fffe6ffd700 (LWP 12523)]
[New Thread 0x7fffe67fc700 (LWP 12524)]
[New Thread 0x7fffe5ffb700 (LWP 12525)]
[New Thread 0x7fffe57fa700 (LWP 12526)]
[New Thread 0x7fffe4ff9700 (LWP 12527)]
[ INFO] [1447083483.356138142]: Initializing nodelet with 8 worker threads.
[New Thread 0x7fffdbfff700 (LWP 12528)]
[New Thread 0x7fffad0be700 (LWP 12533)]
[New Thread 0x7fffab4d0700 (LWP 12562)]
[New Thread 0x7fffab0cf700 (LWP 12563)]
[New Thread 0x7fffaacce700 (LWP 12565)]
[New Thread 0x7fffaa8cd700 (LWP 12566)]
[New Thread 0x7fffaa0cb700 (LWP 12569)]
[New Thread 0x7fffaa4cc700 (LWP 12567)]
[New Thread 0x7fffa9cca700 (LWP 12570)]
*** Error in `/home/wkentaro/ros/indigo/devel/lib/jsk_perception/slic_super_pixels': munmap_chunk(): invalid pointer: 0x00007fff9f5674a0 ***

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffec974700 (LWP 12519)]
0x00007ffff6d83cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by garaemon** [comment]
give me gdb output

**Comment by wkentaro** [comment]
not repriduced in your environment?

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1378

**Comment by garaemon** [comment]
> not repriduced in your environment?

I have seen SEGV a lot of times.

**Comment by garaemon** [comment]
I think slic does not need to release `cv::Mat`.

https://github.com/garaemon/SLIC-Superpixels/blob/master/slic.cpp#L24

**Comment by garaemon** [comment]
https://github.com/garaemon/SLIC-Superpixels/pull/1

It may solve the issue.

**Comment by wkentaro** [comment]
It does not work, but I don't use this node so it's ok.
this node maybe works only for small images. 
**360x486**
[![image](https://cloud.githubusercontent.com/assets/4310419/11762447/fa747d16-a129-11e5-8840-0cf9e717b265.png)

**1080x1920**
![image](https://cloud.githubusercontent.com/assets/4310419/11762452/15b5e10a-a12a-11e5-8541-433b2a38f97f.png)

**Comment by garaemon** [comment]
I confirmed this issue.

**Comment by garaemon** [comment]
Is it easy to rewrite it with scikit image?

**Comment by wkentaro** [comment]
> Is it easy to rewrite it with scikit image?

Probably, but I don't have the motivation for that now, because I'm not using `slic` currently.
And `slic` seems used with other algorithms and in that case it does not need to be a standalone node.
http://scikit-image.org/docs/dev/api/skimage.segmentation.html?highlight=slic#skimage.segmentation.slic

**Comment by Ridhwanluthra** [comment]
is this solved?

**Comment by wkentaro** [comment]
@Ridhwanluthra I think it has not fixed yet.
