### ISSUE TITLE
How to use Skeletonization?

### ISSUE THREAD

**Issue by rkoyama1623** [jsk-ros-pkg/jsk_recognition#1316]
@iKrishneel 

I am trying to recognize truss, so I want to use skeltonization.
I tried skeltonization.launch by using following picture.

* topoic name: /image_raw
![image_raw](https://cloud.githubusercontent.com/assets/11606776/11162795/c9934bdc-8af4-11e5-99c1-52dffef25147.png)

and edge_detector and dilate_mask_image output following pictures.

* topic name: /edge/image
![edge_image](https://cloud.githubusercontent.com/assets/11606776/11162799/14051bd2-8af5-11e5-9bfc-02c80ecc43ac.png)

* topoic name: /dilate_mask_image/output
![dilate_image](https://cloud.githubusercontent.com/assets/11606776/11162801/284c5db2-8af5-11e5-917a-7203ea4c8ae3.png)

However, skeletonization does not output good results. The output is empty as follows.
* topic name: /skeltonization/image_output
![skeltonized_image](https://cloud.githubusercontent.com/assets/11606776/11162812/9dcb1448-8af5-11e5-925d-b5263be0b309.png)

Does anyone have good idea?
skeltonization.launch's contents is
```
<launch>
  <node pkg="jsk_perception" type="edge_detector" name="edge_detector">
    <remap from="image" to="/image_raw" />
  </node>
  <node pkg="jsk_perception" type="dilate_mask_image" name="dilate_mask_image">
    <remap from="~input" to="/edge/image" />
  </node>
  <node pkg="jsk_perception" type="skeletonization" name="skeletonization">
    <remap from="~input" to="/dilate_mask_image/output" />
  </node>
  <node pkg="image_view" type="image_view" name="edge_view" >
    <remap from="image" to="/edge/image" />
  </node>
  <node pkg="rqt_reconfigure" type="rqt_reconfigure" name="edge_reconfigure" />
</launch>
```

**Comment by wkentaro** [comment]
> However, skeletonization does not output good results. The output is empty as follows.

What kind of output do you expect?
I think that output is normal, because the input image is very simple.
Maybe you can change the params with `rqt_reconfigure`. or try more complex input image.

**Comment by rkoyama1623** [comment]
最終的に，赤い線のような画像が出て欲しいです．
hough_lineを適応する前処理として，細線化をしたくて，issueを立てました．

![good_result](https://cloud.githubusercontent.com/assets/11606776/11162927/c867440e-8afc-11e5-9a22-673f0c16cd89.png)

**Comment by iKrishneel** [comment]
@rkoyama1623 
I tried the node and its working.

As @wkentaro said, can you try to increase the dilate_mask_image in rqt_reconfigure, perhaps by large amount until both sides of the edges fades as one. Please try to confirm using live stream on Xtion sensor.

@wkentaro 
The output will be single pixel wide skeleton of the edge.

Input edge
![screenshot from 2015-11-14 18 28 45](https://cloud.githubusercontent.com/assets/9315167/11162936/9f712bae-8afd-11e5-9db6-f5763a7f7606.png)

Dilated Edges
![screenshot from 2015-11-14 18 28 54](https://cloud.githubusercontent.com/assets/9315167/11162938/ab1d5c20-8afd-11e5-9e2b-d5a7afe40778.png)

Skeleton
![screenshot from 2015-11-14 18 28 40](https://cloud.githubusercontent.com/assets/9315167/11162939/b6635e0e-8afd-11e5-8819-59c09a9ef442.png)

**Comment by wkentaro** [comment]
yeah, I browsed your reference a bit.
http://rosettacode.org/wiki/Zhang-Suen_thinning_algorithm

On Sat, Nov 14, 2015 at 6:30 PM, Krishneel <notifications@github.com> wrote:

> @rkoyama1623 <https://github.com/rkoyama1623>
> I tried the node and its working.
>
> As @wkentaro <https://github.com/wkentaro> said, can you try to increase
> the dilate_mask_image in rqt_reconfigure, perhaps by large amount until
> both sides of the edges fades as one. Please try to confirm using live
> stream on Xtion sensor.
>
> @wkentaro <https://github.com/wkentaro>
> The output will be single pixel wide skeleton of the edge.
>
> Input edge
> [image: screenshot from 2015-11-14 18 28 45]
> <https://cloud.githubusercontent.com/assets/9315167/11162936/9f712bae-8afd-11e5-9db6-f5763a7f7606.png>
>
> Dilated Edges
> [image: screenshot from 2015-11-14 18 28 54]
> <https://cloud.githubusercontent.com/assets/9315167/11162938/ab1d5c20-8afd-11e5-9e2b-d5a7afe40778.png>
>
> Skeleton
> [image: screenshot from 2015-11-14 18 28 40]
> <https://cloud.githubusercontent.com/assets/9315167/11162939/b6635e0e-8afd-11e5-8819-59c09a9ef442.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1316#issuecomment-156676508>
> .
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by rkoyama1623** [comment]
Thank you for advices.
I changed picture to my webcam, and the Dilated Edges are as follows:
![image](https://cloud.githubusercontent.com/assets/11606776/11163012/1fd3e562-8b02-11e5-9415-6700aa3d1459.png)

but still /skeltonization/image_output is black.
I also checked jsk_perception version, but it was latest.

> Please try to confirm using live stream on Xtion sensor.

my input image is 2D. Is it OK?

**Comment by wkentaro** [comment]
@rkoyama1623 
It works if the input image is 2D mono.
I tried use image you attached llike
```
wget https://cloud.githubusercontent.com/assets/11606776/11163012/1fd3e562-8b02-11e5-9415-6700aa3d1459.png -O koyama.png
rosrun jsk_perception image_publisher _file_name:=koyama.png
rosrun jsk_perception skeletonization \~input:=/image_publisher/output
rosrun image_view image_view image:=/skeletnization/image_output
```
![image](https://cloud.githubusercontent.com/assets/4310419/11163029/334f90b8-8b03-11e5-9905-8d40c59484b1.png)

**Comment by iKrishneel** [comment]
@rkoyama1623 
my input image is 2D. Is it OK?
- Yes it works only for 2D image space.

Please check input image type. It only takes single channel 8bit input.

**Comment by wkentaro** [comment]
>  It only takes single channel 8bit input.

but there is conversation between input image encoding to 8bit mono one here:
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/skeletonization_nodelet.cpp#L68-L74

so if there is no errors (liks `cv_bridge exception XXXX`), the conversation should be working.

**Comment by wkentaro** [comment]
maybe there is an another reason why the `skeletonization` does not work on @rkoyama1623 's PC.

**Comment by iKrishneel** [comment]
If @rkoyama1623 does not get an exception, the encoding is correct so I am wondering what is the reason it does not work when he runs the node.

**Comment by rkoyama1623** [comment]
@wkentaro solved my pc problem.
my image_view and rqt_image_view was old (hydro), and they cannot display the message with encoding type of 32FC1.
By using rviz, the image was displayed correctly.

The time seem to come when I must update the ros version to indigo.

Thank you for everything, @wkentaro and @iKrishneel !

**Comment by wkentaro** [comment]
@rkoyama1623 
Please add documentation about the output topic's image encoding here:
 http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/nodes/skeletonization.html#publishing-topic.

like http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/nodes/mask_image_to_label.html

**Comment by wkentaro** [comment]
you can change doc here. https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/doc/jsk_perception/nodes/skeletonization.md

**Comment by rkoyama1623** [comment]
OK, I sent PR.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317
