### ISSUE TITLE
hsi_color_filter.lanchはtfを出力しますか？

### ISSUE THREAD

**Issue by ban-masa** [jsk-ros-pkg/jsk_recognition#1360]
```$ roslaunch jsk_pcl_ros hsi_color_filter.launch DEFAULT_NAMESPACE:=/camera/depth_registered INPUT:=points h_min:=40 h_max:=45 s_min:=50```
とすると以下のような結果になるのですが、ロボットモデル上部に表示されているtfは検出されたboxのものなのでしょうか？
![jsk_recog](https://cloud.githubusercontent.com/assets/14898742/11530879/96bd9884-993b-11e5-8c98-df95657ce558.png)

**Comment by YuOhara** [comment]
報告ありがとうございます。

モデルの上部に出ている矢印ですが、こちらはTFでなく（TFなら名前が出るはず）、RvizのDisplays/BoundingBoxのshow coordsの結果だと思われます。

本来なら左下の箱の真ん中に出るべきものですが、表示のプログラム(jsk_rviz_plugins)のプログラムにバグがあって、正しく表示されてないのだと思います。おそらく座標変換が間違えているのかと。

**Comment by YuOhara** [comment]
ちなみにですが、BoundingBoxのTFを出したいということなら、それも可能で、
https://jsk-recognition.readthedocs.org/en/latest/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.html
~publish_tfというrosparamをtrueにすれば、TFが出ます。

**Comment by garaemon** [comment]
再現するbagファイルを送ってください。
トピックは、`/tf`と`//camera/depth_registered/boxes`です

**Comment by ban-masa** [comment]
遅くなってしまい申し訳ありません。
/tfと/camera/depth_registered/boxesのbagファイルですがこれでよろしいでしょうか。

[hsi_color_filter_test.zip](https://github.com/jsk-ros-pkg/jsk_recognition/files/54386/hsi_color_filter_test.zip)

**Comment by garaemon** [comment]
@ban-mesa 確認してみます

**Comment by garaemon** [comment]
@ban-mesa 

たぶんこれで解決されたんじゃないかと思います
https://github.com/jsk-ros-pkg/jsk_visualization/pull/535

![screenshot from 2015-12-08 15 18 29](https://cloud.githubusercontent.com/assets/40454/11649137/0b39cca0-9dbf-11e5-8f69-0e3025e80e21.png)

**Comment by ban-masa** [comment]
ありがとうございます。
実機で確認したところ、boxの位置に正しく座標系が出るようになりました。
