### ISSUE TITLE
Remove dependency to ml_classifiers

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#1384]
ml_classifiers is not maintained anymore.

**Comment by garaemon** [comment]
```
$ rosdep what-needs ml_classifiers
jsk_pcl_ros
sklearn
$ rosdep what-needs sklearn       
jsk_pcl_ros
```

**Comment by YutoUchimi** [comment]
`ml_classifiers` is already released in kintic, lunar and melodic.
See also https://github.com/jsk-ros-pkg/jsk_recognition/issues/2359
