### ISSUE TITLE
imagesift process is working even after no subscribers for a while

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_recognition#1387]
Imagesift is inheriting nodelet. So, imagesift process sleeps when there are no subscribers.
But, the span time of going to sleep is very slow.
In PR2, it took about 1 minutes before going to sleep.
I want to end working immediately after there are no subscribers.
What should I do? Is there a timeout variable?

**Comment by wkentaro** [comment]
Do you mean the `ConnectionBased` does not work?

**Comment by h-kamada** [comment]
Yes, but I tried again, and this time, it ended immediately. So, something I wrote might be wrong.
