### ISSUE TITLE
Release for jade

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#1395]
now jsk_pcl_ros can compile without ml_classifiers.
Can we release jsk_perception to jade?

https://github.com/jsk-ros-pkg/jsk_recognition/pull/1385

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/issues/1331#issuecomment-157898646 block this, wait a moment

**Comment by k-okada** [comment]
ok, done for indigo
https://github.com/ros/rosdistro/pull/10024

now releasing jade

**Comment by garaemon** [comment]
When I want to add release patch, what can I do?
