### ISSUE TITLE
Do not import child modules from jsk_recogntiion_utils/__init__.py

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#1411]
Difficult to handle matplotlib on all the environment including head-less environment

https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/python/jsk_recognition_utils/__init__.py

https://github.com/jsk-ros-pkg/jsk_recognition/issues/1410

**Comment by wkentaro** [comment]
Fixed via https://github.com/jsk-ros-pkg/jsk_recognition/issues/1410#issuecomment-165045631
