### ISSUE TITLE
jsk_pcl_ros test data is too large (~200M)

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#1413]
Decrease the size.

**Comment by garaemon** [comment]
You can see long log to download it.
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_recognition-jade-deb-false-true/499/console

**Comment by garaemon** [comment]
If we can use wget instead of gdown, we can use --timestamping option to avoid re-download the file (we can cache it somewhere)

**Comment by wkentaro** [comment]
gdown uses wget inside.
https://github.com/wkentaro/gdown/blob/master/gdown/__init__.py#L14

**Comment by wkentaro** [comment]
gdown is necessary to download large file from good drive.
just using wget command does not work.

**Comment by wkentaro** [comment]
@garaemon 
I have done implementation to identify if downloaded file is latest by checking md5 hash. https://github.com/jsk-ros-pkg/jsk_recognition/pull/1419
Do you have any idea how to cache it?

**Comment by wkentaro** [comment]
This is fixed via 
- https://github.com/jsk-ros-pkg/jsk_recognition/commit/cc275d4bfbdabd515b1e794e5eee96ecb85ab6a0
- https://github.com/jsk-ros-pkg/jsk_travis/pull/220
