### ISSUE TITLE
.cfg files need to be fixed and released

### ISSUE THREAD

**Issue by dirk-thomas** [jsk-ros-pkg/jsk_recognition#1558]
Recently you fixed some of the dynamic reconfigure files in this repo (b79ec0a1f8638a87aea774629e465cc38ef7bd94).Other files still need the same fix: e.g. https://github.com/jsk-ros-pkg/jsk_recognition/blob/edc9d417753fec6b1705aaa7ab83e6c888663649/jsk_perception/cfg/PolygonArrayColorLikelihood.cfg#L4-L10 https://github.com/jsk-ros-pkg/jsk_recognition/blob/edc9d417753fec6b1705aaa7ab83e6c888663649/jsk_pcl_ros_utils/cfg/CloudOnPlane.cfg#L6-L12

The fixes also need to be released. Currently the Jade jobs fail since the old code falls back to the non-catkin code generation which won't generate the header in the correct location.

This will likely also be the same for the upcoming Indigo rebuild.

**Comment by k-okada** [comment]
Thanks, fixed in #1559
