### ISSUE TITLE
Coverage of testing ROS nodes

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1571]
## jsk_pcl_ros
- [ ] add_color_from_image_nodelet
- [x] attention_clipper_nodelet
- [ ] bilateral_filter_nodelet
- [ ] border_estimator_nodelet
- [ ] bounding_box_filter_nodelet
- [ ] boundingbox_occlusion_rejector_nodelet
- [ ] capture_stereo_synchronizer_nodelet
- [ ] cluster_point_indices_decomposer_nodelet
- [ ] cluster_point_indices_decomposer_z_axis_nodelet
- [ ] collision_detector_nodelet
- [ ] color_filter_nodelet
- [ ] color_histogram_matcher_nodelet
- [ ] colorize_random_points_RF_nodelet
- [ ] colorize_segmented_RF_nodelet
- [ ] convex_connected_voxels_nodelet
- [ ] depth_calibration_nodelet
- [ ] depth_image_creator_nodelet
- [ ] edge_depth_refinement_nodelet
- [ ] edgebased_cube_finder_nodelet
- [ ] environment_plane_modeling_nodelet
- [x] euclidean_cluster_extraction_nodelet
- [ ] extract_cuboid_particles_top_n_nodelet
- [x] extract_indices_nodelet
- [ ] feature_registration_nodelet
- [ ] find_object_on_plane_nodelet
- [ ] fisheye_sphere_publisher_nodelet
- [ ] geometric_consistency_grouping_nodelet
- [ ] grid_sampler_nodelet
- [ ] handle_estimator_nodelet
- [ ] heightmap_converter_nodelet
- [ ] heightmap_morphological_filtering_nodelet
- [ ] heightmap_time_accumulation_nodelet
- [ ] heightmap_to_pointcloud_nodelet
- [ ] hinted_handle_estimator_nodelet
- [ ] hinted_plane_detector_nodelet
- [ ] hinted_stick_finder_nodelet
- [ ] icp_registration_nodelet
- [ ] image_rotate_nodelet
- [ ] incremental_model_registration_nodelet
- [ ] interactive_cuboid_likelihood_nodelet
- [ ] intermittent_image_annotator_nodelet
- [ ] joint_state_static_filter_nodelet
- [ ] keypoints_publisher_nodelet
- [ ] kinfu_nodelet
- [ ] line_segment_collector_nodelet
- [ ] line_segment_detector_nodelet
- [ ] linemod_nodelet
- [ ] mask_image_cluster_filter_nodelet
- [ ] mask_image_filter_nodelet
- [ ] moving_least_square_smoothing_nodelet
- [ ] multi_plane_extraction_nodelet
- [ ] multi_plane_sac_segmentation_nodelet
- [ ] normal_direction_filter_nodelet
- [ ] normal_estimation_integral_image_nodelet
- [ ] normal_estimation_omp_nodelet
- [ ] octomap_server_contact_nodelet
- [ ] octree_change_publisher_nodelet
- [ ] octree_voxel_grid_nodelet
- [ ] organize_pointcloud_nodelet
- [ ] organized_edge_detector_nodelet
- [ ] organized_multi_plane_segmentation_nodelet
- [ ] organized_pass_through_nodelet
- [ ] organized_pointcloud_to_point_indices_nodelet
- [ ] parallel_edge_finder_nodelet
- [ ] particle_filter_tracking_nodelet
- [ ] plane_supported_cuboid_estimator_nodelet
- [ ] pointcloud_database_server_nodelet
- [ ] pointcloud_localization_nodelet
- [ ] pointcloud_moveit_filter
- [ ] pointcloud_screenpoint_nodelet
- [ ] region_adjacency_graph
- [ ] region_growing_multiple_plane_segmentation_nodelet
- [ ] region_growing_segmentation_nodelet
- [ ] resize_points_publisher_nodelet
- [ ] roi_clipper_nodelet
- [ ] selected_cluster_publisher_nodelet
- [ ] snapit_nodelet
- [ ] supervoxel_segmentation_nodelet
- [ ] tilt_laser_listener_nodelet
- [ ] torus_finder_nodelet
- [ ] uniform_sampling_nodelet
- [ ] viewpoint_sampler
- [ ] voxel_grid_downsample_decoder_nodelet
- [ ] voxel_grid_downsample_manager_nodelet
- [ ] voxel_grid_large_scale_nodelet
## jsk_perception
- [x] add_mask_image
- [x] apply_mask_image
- [x] background_substraction_nodelet
- [x] blob_detector
- [x] bounding_box_to_rect
- [x] calc_flow
- [ ] camshiftdemo
- [x] color_histogram
- [ ] color_histogram_label_match
- [ ] color_histogram_sliding_matcher
- [x] colorize_float_image
- [x] colorize_labels
- [ ] contour_finder
- [ ] edge_detector
- [ ] fisheye_to_panorama
- [ ] gaussian_blur
- [ ] grabcut_nodelet
- [x] grid_label
- [ ] histogram_of_oriented_gradients
- [ ] hough_circles
- [ ] hough_lines
- [ ] hsv_decomposer
- ~~image_utils~~
- [x] kmeans
- [ ] lab_decomposer
- [ ] linemod
- [ ] mask_image_generator
- [ ] mask_image_to_rect
- [ ] mask_image_to_roi
- [ ] morphological_operator
- [x] multiply_mask_image
- [ ] oriented_gradient
- [ ] oriented_gradient_node
- [ ] point_pose_extractor
- [ ] polygon_array_color_histogram
- [ ] polygon_array_color_likelihood
- [ ] polygon_array_to_label_image
- [ ] polygon_to_mask_image
- [ ] project_image_point
- [ ] rectangle_detector
- [ ] rect_array_actual_size_filter
- [ ] rect_to_mask_image
- [ ] rect_to_roi
- [ ] rgb_decomposer
- [ ] robot_to_mask_image
- [ ] roi_to_mask_image
- [ ] roi_to_rect
- [ ] saliency_map_generator_node
- [ ] single_channel_histogram
- [ ] single_nodelet_exec.in
- [ ] skeletonization_nodelet
- [x] slic_superpixels
- [ ] sliding_window_object_detector
- [ ] sliding_window_object_detector_trainer_node
- [ ] snake_segmentation
- [x] sparse_image_decoder
- [x] sparse_image_encoder
- [ ] tabletop_color_difference_likelihood
- [ ] unapply_mask_image
- [ ] virtual_camera_mono
- [ ] white_balance_converter
- [ ] ycc_decomposer
- [ ] binpack_rect_array.py
- [x] bof_histogram_extractor.py
- ~~create_feature0d_dataset.py~~
- [x] draw_rect_array.py
- ~~extract_images_sync~~
- fast_rcnn_caffenet.py (too difficult on travis)
- [x] fisheye_ray.py
- [x] image_publisher.py
- ~~image_saver_sync~~
- [ ] image_time_diff.py
- [x] image_to_label.py
- [x] label_image_decomposer.py
- [x] mask_image_to_label.py
- [x] matchtemplate.py
- [ ] non_maximum_suppression.py
- ~~publish_header~~
- [x] random_forest_server.py
- [x] rect_array_to_image_marker.py
- [x] selective_search.py
- [x] sklearn_classifier.py
- [ ] solidity_rag_merge.py
- [x] split_fore_background.py
- [x] tile_image.py
- [ ] unwrap_histogram_with_range_array.py

**Comment by YutoUchimi** [comment]
Update on 2019/4/22

checkerboard_detector
=====================

node (under src/ directory)
---------------------------

- [ ] checkerboard_calibration.cpp
- [ ] checkerboard_detector.cpp
- [ ] objectdetection_tf_publisher.py
- [ ] objectdetection_transform_echo.cpp


imagesift
=========

nodelet (declared in nodelet.xml)
---------------------------------

- [x] ImageSift


jsk_pcl_ros
===========

nodelet (declared in libjsk_pcl_ros.xml)
----------------------------------------

- [x] AddColorFromImage
- [x] AddColorFromImageToOrganized
- [x] AttentionClipper
- [x] BilateralFilter
- [ ] BorderEstimator
- [x] BoundingBoxFilter
- [ ] BoundingBoxOcclusionRejector
- [ ] CaptureStereoSynchronizer
- [x] ClusterPointIndicesDecomposer
- [ ] ClusterPointIndicesDecomposerZAxis
- [x] ConvexConnectedVoxels
- [ ] CollisionDetector
- [x] ColorBasedRegionGrowingSegmentation
- [x] ColorHistogram
- [x] ColorHistogramClassifier
- [x] ColorHistogramFilter
- [ ] ColorHistogramMatcher
- [x] ColorizeMapRandomForest
- [x] ColorizeRandomForest
- [ ] DepthCalibration
- [x] DepthImageCreator
- [x] EdgebasedCubeFinder
- [x] EdgeDepthRefinement
- [x] EuclideanClustering
- [x] EnvironmentPlaneModeling
- [ ] ExtractCuboidParticlesTopN
- [ ] ExtractIndices
- [ ] FeatureRegistration
- [x] FindObjectOnPlane
- [ ] FisheyeSpherePublisher
- [ ] FuseDepthImages
- [ ] FuseRGBImages
- [ ] GridSampler
- [x] HandleEstimator
- [ ] HeightmapConverter
- [ ] HeightmapMorphologicalFiltering
- [ ] HeightmapTimeAccumulation
- [ ] HeightmapToPointCloud
- [ ] HintedHandleEstimator
- [ ] HintedPlaneDetector
- [ ] HintedStickFinder
- [x] HSIColorFilter
- [ ] ICPRegistration
- [ ] ImageRotateNodelet
- [ ] IncrementalModelRegistration
- [x] InteractiveCuboidLikelihood
- [ ] IntermittentImageAnnotator
- [ ] JointStateStaticFilter
- [ ] KeypointsPublisher
- [x] Kinfu
- [ ] LineMODDetector
- [ ] LineMODTrainer
- [ ] LineSegmentCollector
- [x] LineSegmentDetector
- [ ] MaskImageClusterFilter
- [ ] MaskImageFilter
- [ ] MovingLeastSquareSmoothing
- [x] MultiPlaneSACSegmentation
- [ ] MultiPlaneExtraction
- [ ] NormalDirectionFilter
- [ ] NormalEstimationIntegralImage
- [ ] NormalEstimationOMP
- [x] OctomapServerContact
- [ ] OctreeChangePublisher
- [x] OctreeVoxelGrid
- [ ] OrganizedEdgeDetector
- [ ] OrganizedMultiPlaneSegmentation
- [ ] OrganizedPassThrough
- [ ] ParallelEdgeFinder
- [ ] ParticleFilterTracking
- [ ] PeopleDetection
- [ ] PlaneSupportedCuboidEstimator
- [x] PointcloudDatabaseServer
- [ ] PointCloudLocalization
- [x] PointcloudScreenpoint
- [x] PrimitiveShapeClassifier
- [x] PPFRegistration
- [x] RearrangeBoundingBox
- [ ] RegionGrowingMultiplePlaneSegmentation
- [ ] RegionGrowingSegmentation
- [ ] ResizePointsPublisher
- [ ] RGBColorFilter
- [ ] ROIClipper
- [x] SelectedClusterPublisher
- [ ] Snapit
- [ ] SupervoxelSegmentation
- [ ] TargetAdaptiveTracking
- [ ] TiltLaserListener
- [ ] TorusFinder
- [x] VoxelGridDownsampleDecoder
- [x] VoxelGridDownsampleManager
- [ ] VoxelGridLargeScale

node (under scripts/ directory)
-------------------------------

- [ ] calculate_polygon_from_imu.py
- [x] color_histogram_visualizer.py
- [ ] depth_error_calibration.py
- [x] detect_graspable_poses_pcabase.py
- [x] draw_3d_circle.py
- [ ] dump_depth_error.py
- [ ] extract_top_polygon_likelihood.py
- [ ] in_hand_recognition_manager.py
- [ ] marker_appender.py
- [ ] plane_time_ensync_for_recognition.py
- [ ] publish_clicked_point_bbox.py
- [ ] renew_tracking.py
- [ ] snapit_sample_pose_publisher.py
- [ ] test_contact_sensor.py
- [ ] tower_detect_viewer_server.py
- [ ] tracker_status_info.py
- [ ] tracking_info.py

node (under euslisp/ directory)
-------------------------------

- [ ] collision-detector-client.l
- [ ] display-bounding-box-array.l
- [ ] handle_estimator.l
- [ ] pointcloud_screenpoint.l
- [ ] publish-sensor-for-octomap-pr2.l
- [ ] store-pointcloud.l


jsk_pcl_ros_utils
=================

nodelet (declared in jsk_pcl_nodelets.xml)
------------------------------------------

- [x] AddPointIndices
- [x] BoundingBoxArrayToBoundingBox
- [x] CentroidPublisher
- [ ] CloudOnPlane
- [x] ClusterPointIndicesToPointIndices
- [ ] ColorizeDistanceFromPlane
- [ ] ColorizeHeight2DMapping
- [ ] DelayPointCloud
- [ ] DepthImageError
- [ ] LabelToClusterPointIndices
- [ ] MarkerArrayVoxelToPointCloud
- [ ] MaskImageToDepthConsideredMaskImage
- [ ] MaskImageToPointIndices
- [x] NormalConcatenater
- [ ] NormalFlipToFrame
- [ ] PCDReaderWithPose
- [ ] PlanarPointCloudSimulator
- [ ] PlaneConcatenator
- [x] PlaneReasoner
- [x] PlaneRejector
- [ ] PointCloudRelativeFromPoseStamped
- [ ] PointCloudToClusterPointIndices
- [x] PointCloudToMaskImage
- [x] PointCloudToPCD
- [x] PointCloudToPointIndices
- [ ] PointCloudToSTL
- [ ] PointCloudXYZRGBToXYZ
- [x] PointCloudXYZToXYZRGB
- [x] PointIndicesToClusterPointIndices
- [x] PointIndicesToMaskImage
- [x] PolygonAppender
- [ ] PolygonArrayAngleLikelihood
- [ ] PolygonArrayAreaLikelihood
- [ ] PolygonArrayDistanceLikelihood
- [ ] PolygonArrayFootAngleLikelihood
- [x] PolygonArrayLikelihoodFilter
- [ ] PolygonArrayTransformer
- [x] PolygonArrayUnwrapper
- [ ] PolygonArrayWrapper
- [ ] PolygonFlipper
- [x] PolygonMagnifier
- [ ] PolygonPointsSampler
- [ ] PoseWithCovarianceStampedToGaussianPointCloud
- [ ] SphericalPointCloudSimulator
- [x] StaticPolygonArrayPublisher
- [x] SubtractPointIndices
- [ ] TfTransformBoundingBox
- [ ] TfTransformBoundingBoxArray
- [ ] TfTransformCloud
- [x] TransformPointcloudInBoundingBox

node (under scripts/ directory)
-------------------------------

- [ ] cloud_on_plane_info.py
- [x] evaluate_box_segmentation_by_gt_box.py
- [x] evaluate_voxel_segmentation_by_gt_box.py


jsk_perception
==============

nodelet (declared in libjsk_perception.xml)
-------------------------------------------

- [x] AddMaskImage
- [x] ApplyMaskImage
- [x] BackgroundSubstraction
- [x] Bing
- [ ] BlackHat
- [x] BlobDetector
- [x] BoundingBoxToRect
- [x] BoundingObjectMaskImage
- [x] BoundingRectMaskImage
- [ ] Closing
- [x] ColorHistogram
- [ ] ColorHistogramLabelMatch
- [x] ColorizeFloatImage
- [x] ColorizeLabels
- [x] ConcaveHullMaskImage
- [x] ConsensusTracking
- [ ] ContourFinder
- [x] ConvexHullMaskImage
- [ ] DilateMaskImage
- [x] DrawRects
- [ ] ErodeMaskImage
- [x] FilterMaskImageWithSize
- [ ] FisheyeToPanorama
- [x] FlowVelocityThresholding
- [ ] GaussianBlur
- [ ] GrabCut
- [x] GridLabel
- [ ] HSVDecomposer
- [x] KMeans
- [ ] LabDecomposer
- [x] LabelToMaskImage
- [x] MaskImageGenerator
- [x] MaskImageToRect
- [ ] MaskImageToROI
- [ ] MorphologicalGradient
- [x] MultiplyMaskImage
- [ ] Opening
- [x] OverlayImageColorOnMono
- [ ] PolygonArrayColorHistogram
- [ ] PolygonArrayColorLikelihood
- [ ] PolygonArrayToLabelImage
- [ ] PolygonToMaskImage
- [ ] ProjectImagePoint
- [x] RectArrayActualSizeFilter
- [x] RectArrayToDensityImage
- [ ] RectToMaskImage
- [ ] RectToROI
- [ ] RGBDecomposer
- [ ] RobotToMaskImage
- [ ] ROIToMaskImage
- [ ] ROIToRect
- [ ] SaliencyMapGenerator
- [ ] SingleChannelHistogram
- [ ] Skeletonization
- [x] SLICSuperPixels
- [ ] SlidingWindowObjectDetector
- [ ] SnakeSegmentation
- [x] SparseImageDecoder
- [x] SparseImageEncoder
- [x] SubtractMaskImage
- [ ] TabletopColorDifferenceLikelihood
- [ ] TopHat
- [ ] UnapplyMaskImage
- [ ] YCCDecomposer

node (under node_scripts/ directory)
------------------------------------

- [x] alexnet_object_recognition.py
- [ ] apply_context_to_label_probability
- [ ] binpack_rect_array.py
- [x] bof_histogram_extractor.py
- [x] deep_sort_tracker_node.py
- [x] draw_classification_result.py
- [x] extract_image_channel.py
- [x] face_pose_estimation.py
- [ ] fast_rcnn.py
- [ ] fcn_depth_prediction.py
- [x] fcn_object_segmentation.py
- [x] fisheye_ray.py
- [x] human_mesh_recovery.py
- [x] image_cluster_indices_decomposer.py
- [x] image_publisher.py
- [ ] image_time_diff.py
- [x] image_to_label.py
- [x] label_image_classifier.py
- [x] label_image_decomposer.py
- [x] mask_image_to_label.py
- [ ] mask_rcnn_instance_segmentation.py
- [x] matchtemplate.py
- [ ] non_maximum_suppression.py
- [ ] people_mask_publisher.py
- [x] people_pose_estimation_2d.py
- [ ] pointit.py
- [x] probability_image_classifier.py
- [x] random_forest_server.py
- [x] rect_array_to_image_marker.py
- [x] regional_feature_based_object_recognition.py
- [x] selective_search.py
- [x] sklearn_classifier.py
- [ ] solidity_rag_merge.py
- [x] speak_when_label_found.py
- [x] split_fore_background.py
- [x] ssd_object_detector.py
- [x] tile_image.py
- [ ] unwrap_histogram_with_range_array.py
- [x] vgg16_object_recognition.py

node (under euslisp/ directory)
-------------------------------

- [ ] detection_interface.l
- [ ] kalman-filtered-objectdetection-marker.l
- [ ] objectdetection-marker.l


jsk_recognition_msgs
====================

node (under scripts/ directory)
-------------------------------

- [ ] object_array_publisher.py
- [ ] people_pose_array_to_pose_array.py
- [ ] plot_data_to_csv.py
- [ ] save_mesh_server.py


jsk_recognition_utils
=====================

node (under node_scripts/ directory)
------------------------------------

- [x] add_bounding_box_array.py
- [ ] add_cluster_indices.py
- [x] bouding_box_array_publisher.py
- [ ] image_16uc1_to_32fc1.py
- [ ] polygon_array_publisher.py
- [ ] polygon_array_to_polygon.py
- [ ] pose_array_to_pose.py
- [ ] rect_arra_to_polygon_array.py
- [ ] static_virtual_camera.py


resized_image_transport
=======================

nodelet (declared in nodelet.xml)
---------------------------------

- [x] ImageResizer
- [ ] LogPolar
