### ISSUE TITLE
[bug] Build status of deb does not appear in README

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1572]
And the links is dead, too.
Anyone who knows how to fix this?

## Status
http://jenkins.ros.org/job/ros-indigo-jsk-recognition_binarydeb_saucy_i386/

<img width="498" alt="screen shot 2016-03-31 at 6 36 51 pm" src="https://cloud.githubusercontent.com/assets/4310419/14171761/9e4b0b1c-f76f-11e5-8e10-2718f3e5a413.png">

**Comment by k-okada** [comment]
build farm has moved to jenkins.ros.org to build.ros org ->  to
http://build.ros.org/job/Ibin_uT64__jsk_perception__ubuntu_trusty_amd64__binary/

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thank you. #1573
