### ISSUE TITLE
jsk_travis is still old: 0.4.2

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1656]
## Issue

0.4.2 has below issues, so we need fix it.

- https://github.com/jsk-ros-pkg/jsk_travis/issues/254
- https://github.com/jsk-ros-pkg/jsk_travis/issues/253

## Solution

Upgrade jsk_travis submodule.

**PRs**

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1640
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1641

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1640
