### ISSUE TITLE
Deprecated nodes/nodelets are not deprecated in actual

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#1724]
@iory 
You changed the documentation for deprecated nodes/nodelets by this [PR](https://github.com/jsk-ros-pkg/jsk_recognition/pull/1696).
Maybe you should also update as below for `edge_detector`:

- `jsk_perception::EdgeDetector` to `edge_detector::EdgeDetector` at [here](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/jsk_perception_nodelets.xml#L189)
- `jsk_perception/EdgeDetector` to `vision_opencv/EdgeDetector` at [here](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/CMakeLists.txt#L142)

and same changes for other deprecated nodes/nodelets.

**Comment by wkentaro** [comment]
@iory What status is this?

**Comment by iory** [comment]
I'm waiting for this.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1726

also https://github.com/ros-perception/opencv_apps/pull/17

**Comment by wkentaro** [comment]
Once this issue is closed, but why is it reopened?

**Comment by k-okada** [comment]
i thought this was wrongly closed by @iory, because there is comment on why you close this, 
but found this was solved in https://github.com/jsk-ros-pkg/jsk_recognition/pull/1859
