### ISSUE TITLE
[jsk_pcl_ros]cluster_decomposer in hsi_color_filter.launch doesn't publish mask image

### ISSUE THREAD

**Issue by Horisu** [jsk-ros-pkg/jsk_recognition#1751]
Original point cloud has width and height.
But after processed color_filter, height is 1 and width seems to be the length of point cloud.
Color_filter uses cloud's height and width to make mask image , so it can't make correct mask image.
How can we fix it?

**Comment by k-okada** [comment]
please write all information that we can reproduce your problem. One of the bast way is to put launch file here.

**Comment by k-okada** [comment]
you can use https://gist.github.com/ to put launch file and add link to here

**Comment by Horisu** [comment]
You need to do is only to make cloud topic and to launch hsi_color_filter.launch .
```bash
roscore
# launch depth camera
roslaunch openni2_launch openni2.launch
# launch hsi_color_filter
roslaunch jsk_pcl_ros hsi_color_filter.launch INPUT:=/camera/depth_registered/points
# configure and make some clusters
rosrun rqt_reconfigure rqt_reconfigure
#mask image never comes
rostopic echo /HSI_color_filter/cluster_decomposer/mask
```
![screenshot from 2016-06-17 18 04 12](https://cloud.githubusercontent.com/assets/9003596/16145864/f9b5ac18-34b5-11e6-9f73-2f412d737c1a.png)

**Comment by iory** [comment]
@Horisu 
Please fetch and try https://github.com/jsk-ros-pkg/jsk_recognition/pull/1752

**Comment by Horisu** [comment]
awesome!

**Comment by wkentaro** [comment]
Fixed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1752
