### ISSUE TITLE
Build failed with opencv-3.x

### ISSUE THREAD

**Issue by mizmizo** [jsk-ros-pkg/jsk_recognition#1778]
indigo,opencv-3.1.0でjsk_perceptionをbuildすると、
```
/home/hiroto/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bounding_rect_mask_image.cpp: In member function ‘virtual void jsk_perception::BoundingRectMaskImage::convert(const ConstPtr&)’:
/home/hiroto/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bounding_rect_mask_image.cpp:73:5: error: ‘vector’ is not a member of ‘cv’
     cv::vector<cv::vector<cv::Point> > contours;
     ^
```
といったようなエラーが出てbuildに失敗します。

http://stackoverflow.com/questions/33400823/opencv-3-0-0-cvvector-missing
を参考に
d592a1c
のようにするとbuildが通るのですが、この方法で解決法として正しいでしょうか？

**Comment by k-okada** [comment]
```
/home/hiroto/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bounding_rect_mask_image.cpp:73:5:
error: ‘vector’ is not a member of ‘cv’
```
bounding_rect_mask_image.cpp の 73行目のcv::vectorをstd::vectorにかえるのでいいんじゃないかな．

--
◉ Kei Okada


On Wed, Jul 13, 2016 at 6:49 PM, Hiroto MIZOHANA <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> indigo,opencv-3.1.0でjsk_perceptionをbuildすると、
>
> /home/hiroto/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bounding_rect_mask_image.cpp: In member function ‘virtual void jsk_perception::BoundingRectMaskImage::convert(const ConstPtr&)’:
> /home/hiroto/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/src/bounding_rect_mask_image.cpp:73:5: error: ‘vector’ is not a member of ‘cv’
>      cv::vector<cv::vector<cv::Point> > contours;
>      ^
>
> といったようなエラーが出てbuildに失敗します。
>
> http://stackoverflow.com/questions/33400823/opencv-3-0-0-cvvector-missing
> を参考に
> d592a1c
> <https://github.com/jsk-ros-pkg/jsk_recognition/commit/d592a1cdb7dc361f7c72daa2233578cc761ae1e1>
> のようにするとbuildが通るのですが、この方法で解決法として正しいでしょうか？
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/1778>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAeG3ITjjMMmpm0vIOaEQ302s1nCBzc_ks5qVLSfgaJpZM4JLPsa>
> .
>



-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Fixed via #1779
