### ISSUE TITLE
jsk_pr2_startupがpackage.xmlに含まれていない

### ISSUE THREAD

**Issue by ban-masa** [jsk-ros-pkg/jsk_recognition#1870]
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/organized_multi_plane_segmentation.launch
のSELF_FILTER_PARAMにおいてjsk_pr2_startupが使用されているのですが、package.xmlに含まれていないためjsk_pr2_startupがない場合、エラーがでて終了します。
デフォルトではSELF_FILTER_PARAMはfalseであり、実行に必須ではないため
```
<arg name="SELF_FILTER_PARAM" default="" />
```
とすることで実行できたのですが、package.xmlにjsk_pr2_startupを含めなくてよいのでしょうか。

**Comment by ban-masa** [comment]
和田さんに教えてもらい、
```
<arg name="SELF_FILTER_PARAM" default="$(find jsk_pr2_startup)/jsk_pr2_sensors/tilt_self_filter.yaml" />
```
を
```
<group if="$(arg RUN_SELF_FILTER)">
```
のあとに移動させることによってエラーなく実行できました。

**Comment by wkentaro** [comment]
変更をPRで送っておいてください :pray:

**Comment by k-okada** [comment]
reopened until PR is merged

**Comment by ban-masa** [comment]
#1873 
遅くなりましたがPR送りました

**Comment by wkentaro** [comment]
Closed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1873
