### ISSUE TITLE
boxのみでpointcloudをclipするnodeが欲しい

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_recognition#1966]
attention clipperは、inputにcamera_infoを必要とするが、laser scanなどを起源とするような点群に対してもboxを指定して切り取るようなことが可能であると良い

**Comment by h-kamada** [comment]
rosbag file: https://drive.google.com/open?id=0B8bpI9nrQ7y3UjQyRUpDY2gxb2s

**Comment by h-kamada** [comment]
https://drive.google.com/open?id=0B8bpI9nrQ7y3VkcwTHZJWElOYkk

**Comment by k-okada** [comment]
box を clip して何がしたいのでしょうか．

--
◉ Kei Okada


2016-11-21 17:51 GMT+09:00 h-kamada <notifications@github.com>:

**Comment by wkentaro** [comment]
There is no boxes, and the frame_id is base_link.. Why?

![image](https://cloud.githubusercontent.com/assets/4310419/20480675/e1ce726e-b026-11e6-9da3-f80cf0efbbbb.png)

**Comment by wkentaro** [comment]
Done.
![image](https://cloud.githubusercontent.com/assets/4310419/20480967/1ad7d9be-b028-11e6-8b66-adad05d29803.png)
https://github.com/wkentaro/jsk_recognition/commits/h-kamada

**Comment by h-kamada** [comment]
base_scanの点群を使ってテーブルの位置認識を行うeusのコードを用いようとしていますが、テーブル周辺に人の足や椅子が多数あるとテーブルの位置に関する誤認識が起こります。
それを防ぐために、/mapにおいてテーブル周辺のみの点群を切り取り、誤認識を防ぐことを考えています。

**Comment by wkentaro** [comment]
@h-kamada ドキュメントでCameraInfoが必要と書いてあるのは間違っていて、PointCloudを使う場合はPointCloudが来ていればOKということだったと思うので、そのように更新お願いします。
http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros/nodes/attention_clipper.html#subscribing-topic

**Comment by h-kamada** [comment]
PR -> #1971
