### ISSUE TITLE
add matchTemplate

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_recognition#2050]
@mizmizo 今日使っていたテンプレートマッチのプログラムをjsk_perceptionにいれてもらえると嬉しいです．
こういう風に使い回しが効くプログラムは重要なので．

**Comment by mizmizo** [comment]
承知しました．
今はeuslibに置いてあって，私としてもこちらに移植したいと考えていたので，
- cudaがないとbuildできないのでcpuだけでも動くようにする．
- documentをつける
の作業が終わり次第PRを出します．

**Comment by iory** [comment]
Close this issue by following PR.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2385
This general template matching program is supported by following commit's diff.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2385/files#diff-f6e60aec1fc1f584e5fea38775271ce9
