### ISSUE TITLE
Reject polygons from polygonarray by likelihood

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_recognition#2052]
I found a nodelet that extracts 1 top likelihood polygonstamped from polygonatrray.
Is there any nodelet that has a function to extract top N polygonarray from original array?
If no, I'll send a pull request.
@wkentaro @k-okada ?

**Comment by wkentaro** [comment]
I'm not sure.

**Comment by furushchev** [comment]
@wkentaro Thanks! Created https://github.com/jsk-ros-pkg/jsk_recognition/pull/2054.
