### ISSUE TITLE
Proposal of introducing docker image ros:indigo + pcl1.8 to make test pass at one time

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#2091]
The CI test fails because of build time of PCL1.8 at the first build, and it passes if we restarted the build thanks to the ccache.

In order to fix this, I propose the use of docker image with ros:indigo + pcl1.8.
We already have the feature of using custom docker image on jsk_travis thanks to @furushchev (https://github.com/jsk-ros-pkg/jsk_travis/pull/307),
so this should be easy to accomplish, and I believe this saves our time at testing PRs on CI.

Any idea?

<img width="1094" alt="screen shot 2017-05-16 at 3 40 55" src="https://cloud.githubusercontent.com/assets/4310419/26073342/8c22667a-39e9-11e7-80de-4bca10c71e7c.png">

- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/228236810
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/227975358
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/222761493
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/224566715

**Comment by wkentaro** [comment]
@k-okada Do you have deb package of PCL1.8?

**Comment by k-okada** [comment]
https://github.com/k-okada/pcl_1_8-release/releases ?

--
◉ Kei Okada


2017-05-18 13:45 GMT+09:00 Kentaro Wada <notifications@github.com>:
