### ISSUE TITLE
[jsk_pcl] Typo in ColorBasedRegionGrowingSegmentation

### ISSUE THREAD

**Issue by Affonso-Gui** [jsk-ros-pkg/jsk_recognition#2096]
Noticed a typo in ColorBasedRegionGrowingSegmentation's parameters.

Wrong: thresho**u**ld
Correct: threshold

![rqt_reconfigure](https://cloud.githubusercontent.com/assets/20625381/26539275/8625b45a-4486-11e7-88c1-ee1bb3fadacb.png)
![terminal](https://cloud.githubusercontent.com/assets/20625381/26539279/8b203480-4486-11e7-9057-bb6f1f29f201.png)

Documentation on read_the_docs states correct spelling.
![readthedocs](https://cloud.githubusercontent.com/assets/20625381/26539336/d55b3130-4486-11e7-9005-7d55278ae172.png)

**Comment by wkentaro** [comment]
@Affonso-Gui Could you please fix this by a PR?

**Comment by Affonso-Gui** [comment]
@wkentaro Pull Request created at #2098

**Comment by k-okada** [comment]
thank you, closed via #2098
