### ISSUE TITLE
Request of releasing 1.1.3

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#2136]
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/2117

We need https://github.com/jsk-ros-pkg/jsk_recognition/issues/2117 in other project.

**Comment by k-okada** [comment]
ok, let's wait for 
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/247644449
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/247571214
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/247667512
- https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/241978259

**Comment by wkentaro** [comment]
so it's time to release?

**Comment by knorth55** [comment]
now this issue moves to release of `1.1.4`?

**Comment by knorth55** [comment]
Oops, `1.1.3` is not released yet.
@k-okada which PR are you waiting for release of `1.1.3`?

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2150

--
◉ Kei Okada


2017-07-07 11:03 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by wkentaro** [comment]
@k-okada Could you please release 1.1.3?

**Comment by wkentaro** [comment]
Thanks.

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/15455
