### ISSUE TITLE
Appending two jsk_recognition_msgs::BoundingBoxArray

### ISSUE THREAD

**Issue by ptiwari0664** [jsk-ros-pkg/jsk_recognition#2263]
I have two differrent sets of jsk_recognition_msgs::BoundingBoxArray. Lets say A and B. I want to concatenate these two in a set C of the same type.
In set C, first set A should fill and then set B should combine with A.

Please give me suggestions.

**Comment by wkentaro** [comment]
I added a not to achieve this.
Please check https://github.com/jsk-ros-pkg/jsk_recognition/pull/2264.

**Comment by ptiwari0664** [comment]
Thanks a lot wkentaro. But it seems, the function  out_msg.boxes.extend(bboxes_msg.boxes) doesn't work in C++ and neither **jsk_topic_tools import ConnectionBasedTransport** (#include<jsk_topic_tools/ConnectionBasedTransport.h>). 

If you can illustrate this logic in C++. It would be helpful for me.

Thanks in advance

**Comment by wkentaro** [comment]
Ah, I see.
I think you can run `out_msg.boxes.push_back(bboxes_msg.boxes[i])`.

**Comment by wkentaro** [comment]
You're welcome!
