### ISSUE TITLE
jsk_2017_10_semiでbuild error

### ISSUE THREAD

**Issue by taichiH** [jsk-ros-pkg/jsk_recognition#2273]
jsk_recognitionをソースからビルドしようとして、以下の手順でインストールしようとしたら、jsk_2017_10_semiパッケージでエラーが出ます。
ご教示いただけないでしょうか。

git clone https://github.com/jsk-ros-pkg/jsk_recognition.git
rosdep install --ignore-src --from-path . -y -r
catkin build

自分の環境
ros kinetic
pip version 9.0.3

Starting  >>> jsk_2017_10_semi                                                 
_______________________________________________________________________________
Errors     << jsk_2017_10_semi:cmake /home/leus/ros/kinetic/logs/jsk_2017_10_semi/build.cmake.000.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "fetcheus" with any
  of the following names:

    fetcheusConfig.cmake
    fetcheus-config.cmake

  Add the installation prefix of "fetcheus" to CMAKE_PREFIX_PATH or set
  "fetcheus_DIR" to a directory containing one of the above files.  If
  "fetcheus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "fetcheus" with any
  of the following names:

    fetcheusConfig.cmake
    fetcheus-config.cmake

  Add the installation prefix of "fetcheus" to CMAKE_PREFIX_PATH or set
  "fetcheus_DIR" to a directory containing one of the above files.  If
  "fetcheus" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)

cd /home/leus/ros/kinetic/build/jsk_2017_10_semi; catkin build --get-env jsk_2017_10_semi | catkin env -si  /usr/bin/cmake /home/leus/ros/kinetic/src/jsk_demos/jsk_2017_10_semi --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/leus/ros/kinetic/devel/.private/jsk_2017_10_semi -DCMAKE_INSTALL_PREFIX=/home/leus/ros/kinetic/install; cd -

**Comment by taichiH** [comment]
could not resolve dependencies in kinetic
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
jsk_semantic_maps: Cannot locate rosdep definition for [json_prolog]
interactive_behavior_201409: Cannot locate rosdep definition for [face_recognition]
jsk_demo_common: Cannot locate rosdep definition for [pr2_gripper_sensor_msgs]
drc_task_common: Cannot locate rosdep definition for [rviz_animated_view_controller]
jsk_2017_10_semi: Cannot locate rosdep definition for [fetcheus]
jsk_2013_04_pr2_610: Cannot locate rosdep definition for [laser_filters_jsk_patch]
jsk_pcl_ros: Cannot locate rosdep definition for [ml_classifiers]
detect_cans_in_fridge_201202: Cannot locate rosdep definition for [pr2_gripper_sensor_msgs]
jsk_perception: Cannot locate rosdep definition for [ml_classifiers]
jsk_pcl_ros_utils: Cannot locate rosdep definition for [ml_classifiers]
drc_com_common: Cannot locate rosdep definition for [jsk_robot_utils]
jsk_2011_07_pr2_semantic: Cannot locate rosdep definition for [pr2_gripper_sensor_action]

```

**Comment by k-okada** [comment]
Sorry, please add `-r` option

--
◉ Kei Okada


2018-04-25 18:29 GMT+09:00 TaichiHigashide <notifications@github.com>:

**Comment by taichiH** [comment]
Thanks, now I successfully built `jsk_perception`, thanks!
