### ISSUE TITLE
virtual_camera_mono occasionally does not work?

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_recognition#2288]
I found that `virtual_mono_camera` occasionally publishes noised images (though I don't know if it is a bug or just a result from passing invalid parameters)

![invalid_panel_camera](https://user-images.githubusercontent.com/1901008/39951768-0a9c595c-55c8-11e8-9e0b-8995b9cbcfbe.png)

This node subscribes following messages:

```
Subscriptions: 
 * /tf [tf2_msgs/TFMessage]
 * /target_polygon [unknown type]
 * /tf_static [unknown type]
 * /view_point [unknown type]
 * /narrow_stereo/left/image_raw [unknown type]
 * /narrow_stereo/left/camera_info [unknown type]
```

We need to record `/view_point` and `/target_polygon` into bagfile on next time.

**Comment by furushchev** [comment]
CC: @Affonso-Gui It was the positional problem that PR2 did not find 7th floor yesterday. (He could not find `↑ 7` on his camera (center))

**Comment by YutoUchimi** [comment]
This is not a noise but the result of interpolation.
It occurs when the input image is enlarged too much.

I created a PR to enable changing the interpolation method in #2470 , so please try it.
