### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Affonso-Gui** [jsk-ros-pkg/jsk_recognition#2346]
Maybe would be nice to release `1.2.6`.

Already have around 120 commits since `1.2.5`, while other releases seem to have an average of 60 commits in between.

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/milestone/8

**Comment by YutoUchimi** [comment]
Merged
https://github.com/ros/rosdistro/pull/19397
https://github.com/ros/rosdistro/pull/19400
