### ISSUE TITLE
How to show text on box?

### ISSUE THREAD

**Issue by jinfagang** [jsk-ros-pkg/jsk_recognition#2407]
I want draw some text on bounding box like this:

![image](https://user-images.githubusercontent.com/21303438/54329027-07de2000-464b-11e9-9246-b49d98b0f723.png)

Is this avaiable in jsk? Someone kindly tell me how to add it? I can not found such a field to draw text on bounding box

**Comment by iory** [comment]
Thanks for your issue report.
I think that you should ask this topic in jsk_visualization here
https://github.com/jsk-ros-pkg/jsk_visualization
