### ISSUE TITLE
[jsk_pcl_ros] ClusterPointIndicesDecomposer does not work if align_boxes is enabled

### ISSUE THREAD

**Issue by jcarlosgm30** [jsk-ros-pkg/jsk_recognition#2436]
ClusterPointIndicesDecomposer works if align_boxes is disabled, but when I enable it, it doesn't publish anything through the topics. I am reviewing the issues for some related it, but I didn't find anything. 

Would anyone know what it could be?

I pasted the launch code.

`
<launch>
  <arg name="manager" default="lidar_nodelet_manager" />
  <arg name="create_manager" default="true" />

  <group ns="pcl_nodelet">
     <node if="$(arg create_manager)"
          pkg="nodelet" type="nodelet" name="$(arg manager)"
          args="manager" output="screen"/>
     <node pkg="nodelet" type="nodelet"
          name="clustering"
          args="load jsk_pcl/EuclideanClustering $(arg manager)"
          output="screen" clear_params="true">
      <remap from="~input" to="/passthrough/output" />
      <remap from="~output" to="/indices/output" />
      <rosparam>
         tolerance: 0.2
      </rosparam>
    </node>

    <node name="cluster_point_indices_decomposer"
        pkg="nodelet" type="nodelet"
        args="standalone jsk_pcl/ClusterPointIndicesDecomposer">
      <remap from="~input" to="/passthrough/output" />
      <remap from="~target" to="/indices/output" />
      <rosparam>
        queue_size: 10
        publish_tf: true
        publish_clouds: false
        use_pca: true
        sort_by: z_axis
        align_boxes: true
      </rosparam>
    </node>
    
  </group>

</launch>`

**Comment by knorth55** [comment]
probably, your inputs are not synchronized.
you can use `rosrun jsk_topic_tools is_synchronized --queue-size 10 /passthrough/output /indices/output`.
if the command above says `not synchronized`, you can try to set `approximate_sync: true` or set larger queue_size like `queue_size: 100`.
but for more correct debugging, can you give us whole launch file and rosbag file to reproduce the problem?

**Comment by jcarlosgm30** [comment]
@knorth55 thank very much you for the answer!

I have used `rosrun jsk_topic_tools is_synchronized --queue-size 10 /passthrough/output /indices/output` and says `synchronized`. 

If `align_boxes` is disabled, the issue doesn't exist. 

I attached the launch file compressed in the .zip file.
[euclidean_segmentation.launch.zip](https://github.com/jsk-ros-pkg/jsk_recognition/files/3279980/euclidean_segmentation.launch.zip)

A piece of the rosbag file can be download from the following link:
https://drive.google.com/file/d/1IKOR2ZVhkLFs68Ie6VVs8QHB6dZQFm32/view?usp=sharing

On the other hand, if I use the pca algorithm to obtain principal components of a cluster data, would the cluster coordinate frame be in tune with principal components, right? However, the clusters coordinate frames are aligned with my sensor frame.

**Comment by knorth55** [comment]
Do you set rosparam `target_frame_id` for `align_boxes`?
you need to set correct `target_frame_id: /robot_frame_id` and `align_boxes_with_plane: false`.
so your node should be like below.

```
<node name="cluster_point_indices_decomposer"
    pkg="nodelet" type="nodelet"
    args="standalone jsk_pcl/ClusterPointIndicesDecomposer">
  <remap from="~input" to="/passthrough/output" />
  <remap from="~target" to="/indices/output" />
  <rosparam>
    queue_size: 10
    publish_tf: true
    publish_clouds: false
    use_pca: true
    sort_by: z_axis
    align_boxes: true
    align_boxes_with_plane: false
    target_frame_id: /robot_frame_id
  </rosparam>
</node>
```

**Comment by jcarlosgm30** [comment]
There was the key!! I don't set `target_frame_id` param. 

I understood that if `align_boxes: true` and `align_boxes_with_plane: true`, bounding box was created depending on pca components, and therefore, It isn't necessary setting `target_frame_id` param. But, with that configuration (`align_boxes: true`, `align_boxes_with_plane: false` and `target_frame_id: /velodyne`), bounding box are published and also, depending on trend of cluster point cloud.

Thank you very much!! @knorth55
