### ISSUE TITLE
Request of release 1.2.11

### ISSUE THREAD

**Issue by YutoUchimi** [jsk-ros-pkg/jsk_recognition#2460]
There are already about 700 commits from 1.2.10.
And https://github.com/jsk-ros-pkg/jsk_visualization/pull/740 is waiting for `jsk_recognition_msgs` to be released.

**Comment by knorth55** [comment]
:+1: I'm waiting for new features.

**Comment by k-okada** [comment]
created milestone, https://github.com/jsk-ros-pkg/jsk_recognition/milestone/10
