### ISSUE TITLE
Add support for ROS noetic?

### ISSUE THREAD

**Issue by raysworld** [jsk-ros-pkg/jsk_recognition#2515]
I am trying to use this package with Ubuntu 20.04 LTS + ROS neotic. Unfortunately I cannot find the available package to install. Would you be very kind to add support for that? Or if this has already been in progress, could you please let me know the status? Many thanks for your help.

**Comment by knorth55** [comment]
@raysworld we are working on it, but before releasing jsk_recognition, we need to change all dependencies to support Ubuntu 20.04 + ROS noetic.
it would be not a easy task and may take several weeks or months.
If you want to try it now, you can maybe try this PR #2507 (but be careful, it is work in progress) and build this package from source.

**Comment by JWhitleyWork** [comment]
@knorth55 Any update on this? We have had a request (https://github.com/Autoware-AI/messages/issues/4) to release Autoware.AI messages into `noetic` and they depend on `jsk_recognition_msgs` as well.

**Comment by knorth55** [comment]
@JWhitleyWork we are moving forward for noetic #2507 .
we are preparing for the release.

**Comment by JWhitleyWork** [comment]
Awesome, thanks!

**Comment by Timple** [comment]
Now #2507 is merged, can a noetic release be made?

**Comment by knorth55** [comment]
we need to wait for other dependency releases, so we cannot release it even if the test build succeeded.

**Comment by ttezy** [comment]
Hi @knorth55 @raysworld , is there any update for Noetic support? I found this Issue is closed but I cannot find any instruction for Autoware.ai Noetic version. May I know if it is possible to build Autoware.ai on Ubuntu 20.04 + ROS Noetic?

**Comment by knorth55** [comment]
Im not sure about autoware, but
jsk recognition is already released in noetic

https://github.com/ros/rosdistro/pull/26895
