### ISSUE TITLE
jsk_recognition merge protection setting may be wrong and PR stays hanging.

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_recognition#2567]
maybe `jsk_recognition` has branch protection setting, which causes this hanging problem.
all PR is waiting response from `continuous-integration/travis-ci`, which does not exist any more.

@k-okada 
can you fix merge protection setting?

![jsk_recognition_travis](https://user-images.githubusercontent.com/9300063/104602314-a2cc3900-56be-11eb-9cea-fa3014195f6f.png)

**Comment by k-okada** [comment]
shoud be fixed

**Comment by knorth55** [comment]
@k-okada thank you!.
