### ISSUE TITLE
With cluster_point_indices_decomposer, a few tf of segmentation_decomposeroutput appear in the reference frame instead of the target frame.

### ISSUE THREAD

**Issue by shmpwk** [jsk-ros-pkg/jsk_recognition#2594]
The [cluster_point_indices_decomposer](https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros/nodes/cluster_point_indices_decomposer.html) node publishes tf of each segmentated  bounding box when the parameter of publish_tf is true.
It is expected to show target frame of the bounding box.
The photo shows the each tf of segmentation_decomposeroutput. 
As you can see the photo, a few tf unexpectedly show on the robot head where I set as the reference frame. 
Whenever the unexpected tf appear,  we get nodelet warn saying "segmented cloud size is zero".

![Screenshot from 2021-05-01 14-36-21](https://user-images.githubusercontent.com/42209144/117245377-bd950a00-ae75-11eb-9606-9d2208ffcd93.png)

**Comment by shmpwk** [comment]
My temporary solution is to change [here](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/cluster_point_indices_decomposer_nodelet.cpp#L432) from true to false. 
It blocks publishing topics including tf when segmented cloud size is 0.

**Comment by knorth55** [comment]
can you upload your rosbag file and launch file to reproduce this error?
I think you got the core idea of this error `segmented cloud size is zero`.
You can make a PR with your solution and discuss it.
Your solution looks good to me, so please make a PR.

**Comment by knorth55** [comment]
however, your solution will change the order of output bounding boxes.
I think it is better to skip the tf publication section only.

**Comment by shmpwk** [comment]
> I think it is better to skip the tf publication section only.
Yes, I will.

**Comment by shmpwk** [comment]
Close with #2599
