### ISSUE TITLE
What Eigen version should I use?

### ISSUE THREAD

**Issue by bxc237** [jsk-ros-pkg/jsk_recognition#2605]
Hi, I am also trying to run OrganizedEdgeDetector with ROS kinetic like this one #2366 , but when I `caktin build` the code, There are some errors like `‘eigen_assert_exception’ is not a member of ‘Eigen’
   if (errorCount) EIGEN_THROW_X(Eigen::eigen_assert_exception());
` and some variables are also not declared in the Parallelizer. Therefore, what Eigen version should I use? Thank you!

**Comment by knorth55** [comment]
please check this one.
https://packages.ubuntu.com/en/bionic/libeigen3-dev

**Comment by bxc237** [comment]
Thx, close issue
