### ISSUE TITLE
python-chainercv-mask-rcnn-pip  could not have their rosdep keys resolved

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/jsk_recognition#2609]
`rosdep install` on jsk_perception results in 
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
jsk_perception: Cannot locate rosdep definition for [python-chainercv-mask-rcnn-pip]
```

the cdoe was added on
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2435/files
but it seems we do not have `python-chainercv-mask-rcnn-pip` on rosdep rule.
https://github.com/ros/rosdistro/search?q=python-chainercv-mask-rcnn-pip

@knorth55 are you forget to send PR to ros/rosdistro ?

**Comment by knorth55** [comment]
@k-okada sorry, it was my typo.
