### ISSUE TITLE
Sample data does not exists

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_recognition#2631]
Sample data and Traned data does not exists.

# jsk_perception

## Trained Data

- drill_svm.xml
  + URL: https://drive.google.com/uc?id=0B5hRAGKTOm_KWW11R0FTX0xjTDg

- vgg16_fast_rcnn.chainermodel
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vX015UzB4aC13cVk

- apc2015_sample_bof.pkl.gz
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vemVRaDBOWDVpb28

- vgg_cnn_m_1024.chainermodel
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vZzJuaFRIdDMtLWc

- bvlc_alexnet.chainermodel
  + URL: https://drive.google.com/uc?id=0B5DV6gwLHtyJZkd1ZTRiNUdrUXM

- bvlc_vgg16.chainermodel
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vSlFjQlJFQjM5TEk

- vgg16_bn_apc2015_496000.chainermodel
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vQ2tCN1hoYV84eHM

- apc2015_sample_clf.pkl.gz
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2veFY5ZFNqbzAzNmc

## Sample Data

- 2016-11-11-12-53-06_in_lab.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vdE9IRERDLXRoUWs

- 2016-10-15-23-21-42_moving_bottle.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vTDZOZGhrTTNvc00

- 2017-06-20-12-00-00_people_images_in_lab.bag.tgz
  + URL: https://drive.google.com/uc?id=0B_NiLAzvehC9Yzl4YzB1WnlFcXM

- apc2016_object_imgs_and_masks.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2veVJ4N21tVlB3MGs

- apc2016_object_imgs_and_masks_templates.tgz
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vX0NqcXNGYXEzUlE

- resnet_features_apc2016.npz
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vM3hhOTBGNjA1eTQ

# jsk_pck_ros_utils

## sample data

- 2017-02-05-16-11-09_shelf_bin.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vYWI2NnZrekEwSmc

- bunny_marker_array.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vdW1NMlhiRU9KZDQ

- arc2017_4objects.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vakpvU0wtMFNCTkk

# jsk_pcl_ros

## sample data

- 2016-10-26-02-09-51_coffee_cup.pcd
  + URL: https://drive.google.com/uc?id=0B5DV6gwLHtyJVVQ2TFhVSTJqZ3M

- sample_add_color_from_image_20170319.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vN284RHBXT1duUWM

- stereo_arc2017_objects.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2va1ZvWHJRT3Y5dkk

- 2016-06-24-17-43-57_tabletop.bag.tgz
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vUllPT3VPOHN6LVU

- room73b2_table.bag
  + URL: https://drive.google.com/uc?id=0B9P1L--7Wd2vdXdfMWNSUU9IVEU

- 2016-07-06-12-16-43-person-in-point-cloud.tgz
  + URL: https://drive.google.com/uc?id=0B_NiLAzvehC9cHhnOFd0YUN2N1U

- sample_door_handle_detector.bag
  + URL: https://drive.google.com/uc?id=0B4ysRIwB7GryMGxCTUI0MHhqWFk

- 2017-06-19-19-34-18_tabletop_coffeecup.tgz
  + URL: https://drive.google.com/uc?id=0B5DV6gwLHtyJRTJ0eGdVYk43bEU

**Comment by knorth55** [comment]
@sktometometo I sent you the original data.

**Comment by sktometometo** [comment]
I have uploaded and re-uploaded files above.
