### ISSUE TITLE
Plane coefficients direction is unstable in PlaneConcatenator.

### ISSUE THREAD

**Issue by Tacha-S** [jsk-ros-pkg/jsk_recognition#2655]
Plane coefficients direction flip according to the position of the point cloud TF.
I think this problem is due to not executing [`forceToDirectOrigin`, which is executed in OrganizedMultiPlaneSegmentation](https://github.com/jsk-ros-pkg/jsk_recognition/blob/6ff031d51d425bf77456d89fbe84b61e58da3aea/jsk_pcl_ros/src/organized_multi_plane_segmentation_nodelet.cpp#L139-L160) after refinement.

Is there any plan to implement this in the future?

**Comment by iory** [comment]
Thank you for your reports.

I think it is common to have a node that receives coefficients and aligns them.
How do you expect the plane coefficient direction to be aligned?

**Comment by Tacha-S** [comment]
The expected output is to be aligned to the side where the depth sensor is detecting the plane (or vice versa).
For example, in the case of an optical frame, it should be aligned so that the angle with the unit z is less than pi/2 (or vice versa).

**Comment by k-okada** [comment]
@Tacha-S Can you create PR that enables your request?
