### ISSUE TITLE
EuclideanClustering crashes with cluster_filter=1

### ISSUE THREAD

**Issue by Affonso-Gui** [jsk-ros-pkg/jsk_recognition#2737]
```xml
    <node name="detic_euclidean_clustering"
          pkg="jsk_pcl_ros" type="euclidean_clustering"
          clear_params="true">
      <remap from="~input" to="depth_registered/points"/>
      <remap from="~input/cluster_indices" to="detic_segmentor/indices"/>
      <rosparam>
        multi: true
        tolerance: 0.03
        min_size: 10
        downsample_enable: true
        cluster_filter: 1
        approximate_sync: true
        queue_size: 100
      </rosparam>
    </node>
```

Sometimes fails at `EuclideanClustering::clusteringClusterIndices` with:
```
terminate called after throwing an instance of 'std::out_of_range'
        what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[docker/detic_euclidean_clustering-1] killing on exit
```

I still haven't been able to dive on this.

**Comment by nakane11** [comment]
I haven't run it, but this error seems to occur here.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/7e6b70416d2629a37a41f1779a52d2d05524fe37/jsk_pcl_ros/src/euclidean_cluster_extraction_nodelet.cpp#L207
In case of `cluster_filter: 1`, `output_indices.size()` is 0. `examine_indices.size()` is set to 1.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/7e6b70416d2629a37a41f1779a52d2d05524fe37/jsk_pcl_ros/src/euclidean_cluster_extraction_nodelet.cpp#L195-L202
