### ISSUE TITLE
Coral EdgeTPUHumanPoseEstimator shows doubled bounding box with rect_array_in_panorama_to_bounding_box_array

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_recognition#2746]
[sktometometo](https://github.com/sktometometo) [2 hours ago](https://github.com/jsk-ros-pkg/jsk_demos/pull/1375#issuecomment-1316717304) • 
PanoramaHumanPoseEstitaterでなくてPanoramaObjectDetectorの方使わないとパノラマ画像の切れ目でバグります

--

[knorth55](https://github.com/knorth55) [2 hours ago](https://github.com/jsk-ros-pkg/jsk_demos/pull/1375#issuecomment-1316726363)
@sktometometo

PanoramaHumanPoseEstitaterでなくてPanoramaObjectDetectorの方使わないとパノラマ画像の切れ目でバグります

なるほど，ありがとう！
PanoramaHumanPoseEstimatorでもrectだすように最近したんだけど，それでもダメかな．
まぁObjectDetectorでもいいんだけど．

--

[sktometometo](https://github.com/sktometometo) [10 minutes ago](https://github.com/jsk-ros-pkg/jsk_demos/pull/1375#issuecomment-1316880215)
@sktometometo

PanoramaHumanPoseEstitaterでなくてPanoramaObjectDetectorの方使わないとパノラマ画像の切れ目でバグります

なるほど，ありがとう！
PanoramaHumanPoseEstimatorでもrectだすように最近したんだけど，それでもダメかな．
まぁObjectDetectorでもいいんだけど．

切れ目の部分でマージする処理入ってないので二重になります

--

[knorth55](https://github.com/knorth55) [4 minutes ago](https://github.com/jsk-ros-pkg/jsk_demos/pull/1375#issuecomment-1316889853) • 
@sktometometo

切れ目の部分でマージする処理入ってないので二重になります

もう少し詳しく報告してほしいんだけど，なぜこれはObjectDetectorではうまくいってて，HumanのRects版ではうまくいってないのかな？
どこでObjectDetectorは二重問題を解消しているのかな？
それに気づいた時に，どこかにIssueをだしたのかな？

EDIT： https://github.com/jsk-ros-pkg/jsk_recognition/issues/2746 こちらに移動．

**Comment by sktometometo** [comment]
どちらかというと https://github.com/jsk-ros-pkg/coral_usb_ros の問題なのでそちらにあとでIssue立てておきます.

**Comment by knorth55** [comment]
確認しました，これだね．


https://user-images.githubusercontent.com/9300063/202185042-c1360a59-193d-43af-940d-ae49eeccf105.mp4


https://user-images.githubusercontent.com/9300063/202185055-316d8d66-7a94-4c76-8785-1bb978792a73.mp4

**Comment by knorth55** [comment]
@sktometometo

たぶんこれで解決しました．

https://github.com/jsk-ros-pkg/coral_usb_ros/pull/126
