### ISSUE TITLE
jsk_pcl_ros documentation

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#330]
documentを作る。
* 何をするためのコードか
* パラメータの一覧
* ユースケース
* デモ画像・動画

**Comment by garaemon** [comment]
I'm planning to add doxygen documentation

**Comment by garaemon** [comment]
I think using [readthedocs](https://docs.readthedocs.org) is the best.
However it only support sphinx, we need to add plugin called breathe.

[cppformat](https://github.com/cppformat/cppformat/tree/master/doc) is a good example: http://cppformat.readthedocs.org/en/stable/

**Comment by garaemon** [comment]
readthedocs only supports sphinx and in order to generate c++ documentation, we need to use [breathe](http://breathe.readthedocs.org/)

However, it does not work so well...

**Comment by wkentaro** [comment]
Is this issue done?
I tried breathe and got the doc like:
http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/kmeans.html#_CPPv2N14jsk_perception6KMeansE
(the documentation in source code is https://github.com/wkentaro/jsk_recognition/blob/master/jsk_perception/include/jsk_perception/kmeans.h#L53)

I can transfer the owner of domain jsk-recognition.readthedocs.org to the owner account in the lab.
After confirming the behavior.

**Comment by garaemon** [comment]
Great!

Can you generate the doc on travis and deploy it to readthedoc?
I'd also want to use it on jsk_topic_tools

2015年8月24日月曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Is this issue done?
> I tried breathe and got the doc like:
>
> http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/kmeans.html#_CPPv2N14jsk_perception6KMeansE
> (the documentation in source code is
> https://github.com/wkentaro/jsk_recognition/blob/master/jsk_perception/include/jsk_perception/kmeans.h#L53
> )
>
> I can transfer the owner of domain jsk-recognition.readthedocs.org to the
> owner account in the lab.
> After confirming the behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/330#issuecomment-134076526>
> .
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
How can I generate the doc on travis?
this says readthedoc supports webhooks.
https://read-the-docs.readthedocs.org/en/latest/webhooks.html

**Comment by wkentaro** [comment]
I found that getting http://readthedocs.org/build/<project_name> by `curl` or `wget` triggers rebuild.
Do you prefer travis to GitHub webhooks?

**Comment by garaemon** [comment]
webooks is ok to me.

**Comment by wkentaro** [comment]
Okay, I will talk about this with @k-okada , who seems to have the lab account on readthedoc.

**Comment by k-okada** [comment]
I think we already have auto generated doc on ->
http://docs.ros.org/indigo/api/jsk_perception/html/classjsk__perception_1_1KMeans.html

http://docs.ros.org/indigo/api/jsk_perception/html/index.html

I'm not export on this but may be just to add
https://github.com/ros/ros_comm/blob/indigo-devel/clients/roscpp/include/ros/roscpp.dox
file will create nice index pages as
http://docs.ros.org/indigo/api/roscpp/html/

please check http://wiki.ros.org/rosdoc_lite and
http://jenkins.ros.org/job/doc-indigo-jsk_recognition/

--
◉ Kei Okada

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/724/files
I forget this pr

**Comment by wkentaro** [comment]
so can we separate api doc about c++ class & method and ros usage doc like README?

IMO the READMEs are getting too large, slow to load, hard to search, and a little information about each tools because of that. Why dont we move the READMEs to docs.ros.org or readthedocs? (i dont know how to do it in docs.ros.org though)

**Comment by garaemon** [comment]
We can move to docs.ros.org and doxygen supports markdown from 1.8.0.

**Comment by garaemon** [comment]
According to the template file of rosdoc_lite https://github.com/ros-infrastructure/rosdoc_lite/blob/master/src/rosdoc_lite/templates/doxy.template, doxygen version should be greater than 1.8.0.

**Comment by wkentaro** [comment]
thanks. after talking with also @k-okada .
we will use rosdoc_lite to generate documentation.
I tried and the output will be like below for jsk_perceptiion.

![image](https://cloud.githubusercontent.com/assets/4310419/9464682/c298fdfa-4b60-11e5-836b-19f880ff36de.png)

![image](https://cloud.githubusercontent.com/assets/4310419/9464681/bf696ef8-4b60-11e5-90d6-fd65e9c5dee2.png)

**Comment by wkentaro** [comment]
However, my concern is that there is no searching service at codeapi page on docs.ros.org at present.
This is a big problem, and even in github page we can use `Ctrl-F`. and of cource in Sphinx page there is search form.
Do you know something about this? @garaemon @k-okada

**Comment by garaemon** [comment]
client search? https://www.stack.nl/~dimitri/doxygen/manual/searching.html

**Comment by wkentaro** [comment]
maybe client search cannot be used in rosdoc_lite at present according to [here 2.3.3](http://wiki.ros.org/rosdoc_lite) (because no option for SEARCHENGINE).

**Comment by wkentaro** [comment]
If search function cannot be used, I'd like to use sphinx and readthedocs, because for codeapi we can add link to docs.ros.org/api.

**Comment by k-okada** [comment]
if current version working on rosdoc.yaml, I'll merge this and release them
to see how it works.
--
◉ Kei Okada

**Comment by garaemon** [comment]
hmm, make sense.

@wkentaro Your plan is to use readthedocs to host markdown files only, right?

**Comment by wkentaro** [comment]
Yeah, I will just split README.md with sections like http://jsk-recognition.readthedocs.org/en/latest/ without breathe and doxygen.

**Comment by garaemon** [comment]
How about to write the contents of markdown in header files and
autonatically generates separated markdown?
is it too hacky?

2015年8月25日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Yeah, I will just split README.md with sections like
> http://jsk-recognition.readthedocs.org/en/latest/ without breathe and
> doxygen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/330#issuecomment-134606916>
> .
>


-- 
✉︎ from iPhone

**Comment by garaemon** [comment]
In my opinion, managing separated markdown is not good idea, it requires a
lot of effort to maintain.

2015年8月25日火曜日、Ryohei Ueda<garaemon@gmail.com>さんは書きました:

> How about to write the contents of markdown in header files and
> autonatically generates separated markdown?
> is it too hacky?
>
> 2015年8月25日火曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> Yeah, I will just split README.md with sections like
>> http://jsk-recognition.readthedocs.org/en/latest/ without breathe and
>> doxygen.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_recognition/issues/330#issuecomment-134606916>
>> .
>>
>
>
> --
> ✉︎ from iPhone
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
I'm not so familiar with doxygen so don't know how to do it.
But I think that is better and easy to maintain.

**Comment by wkentaro** [comment]
As discussed here: https://github.com/ros-infrastructure/rosdoc_lite/issues/56
The client search will be available in docs.ros.org like:
![](https://cloud.githubusercontent.com/assets/4310419/9476425/a4745558-4ba7-11e5-9647-adcb66a4d7dd.png)
But I found doxygen does not support full text search with client engine. (it's very poor)
https://www.stack.nl/~dimitri/doxygen/manual/searching.html

**Comment by garaemon** [comment]
Is breathe better than doxygen in searching?

**Comment by wkentaro** [comment]
strictly speaking, sphinx is better than doxygen in terms of text search.
popular themes of sphinx supports full text search.

**Comment by wkentaro** [comment]
if we can use custom theme in docs.ros.org I think full text search is possible. But as described here https://github.com/ros-infrastructure/rosdoc_lite/issues/58#issuecomment-134747020
using custom theme with doxygen seems hard.

**Comment by garaemon** [comment]
discussion is moved to https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092
