### ISSUE TITLE
iai_kinect2は、ubuntu12.04に使うできだ

### ISSUE THREAD

**Issue by cretaceous-creature** [jsk-ros-pkg/jsk_recognition#407]
The source code in github of IAI_kinect2 and Libfreenect2 are changing everyday.
Any one who wants to use the library plz carefully choose a stable commit 
and also a small adjustment should be placed. 
##1##. (Firstly U have to check whether ur GPU card is working or not)
##2##. git clone https://github.com/code-iai/iai_kinect2       to ur catkin workspace and also
install the libfreenect2(https://github.com/OpenKinect/libfreenect2) to any other place. 
I'm using commit 41d35b0f0cb812bd2e0a4f35b676becb5e1d8b26       Fri Oct 31  for iai_kinect2
and 22eeda006eedc03f02815809bb2a7d4ce2351d1f       Thu Oct 9   for libfreenect2.  U can update of course.
##3##.  The packages u need to download( 
automake
libudev-dev
xorg-dev
libturbojpeg
ocl-icd-lib*
ocl-icd-open*(need add trusty repository to ur sourcelist)
opencl-headers
 ....cant remember...              )
##4##. There may be some link error,   locate the library file and ln -s  to the require path  (basically in path  /usr/lib/    /usr/lib/x86*/)
##5##. Sometimes CMakeList also need to fix.
##6##. Firstly compile libfreenect2, then iai_kinect2.  I hope I could create a pull, but I am not familiar with this yet...
##7##.  Good Luck!

**Comment by garaemon** [comment]
nos jsk_pcl_ros works on indigo and we should use 14.04 for this purpose
