### ISSUE TITLE
organized_multi_plane_segmentationでwarningがたくさん出る

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_recognition#446]
おそらく organized_multi_plane_segmentation.launch の中で、
以下のwarningが1秒に1回くらいの割合で出るのですが、抑制できますでしょうか。
平面検出と平面の上の物体検出は正常に動作しています。
```
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
```

**Comment by garaemon** [comment]
solevd by https://github.com/jsk-ros-pkg/jsk_recognition/issues/611
