### ISSUE TITLE
travisのテストが終わらない

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#634]
プログラムが増えてきて、結構な頻度で50分以上のコンパイル時間がかかってしまうようです

どうするのが正解でしょうか？

1. 頑張ってコンパイル時間が短いコードを書く
2. jsk_pcl_rosとjsk_perceptionのテストを分ける(依存をなくす)
3. ほぼnodeletなのだなら、片っ端から.cppをincludeして一つの巨大.cppにしてコンパイルしてしまう

- [x] jsk_recognition_msgsを追加。
- [x] debリリース
- [x] jsk_travisにどのパッケージをコンパイルするかの指示ができるようにする
- [x]  jsk_pcl_rosとjsk_perceptionをjsk_recogntion_msgsを使う形に変更。テストもかえる
- [x]  jsk_control, jsk_visualizationもjsk_recognition_msgsを使うように変更する
- [x] jsk_demosの対応
- [x] relase jsk_recogntiion
- [x] release jsk_rviz_plugins

**Comment by k-okada** [comment]
2ですかね．

--
◉ Kei Okada


2015-01-22 10:37 GMT+09:00 Ryohei Ueda <notifications@github.com>:

**Comment by garaemon** [comment]
メッセージに依存があるのが△なので、jsk_recognition_msgsみたいなものを作ってそこにまとめる方向ですかね。

**Comment by garaemon** [comment]
以下のような手順ですかね

1. jsk_recognition_msgsを追加。

  jsk_commonにあるべきパッケージだが、試行錯誤しやすいようにjsk_recognitionに配置

2. debリリース
3. jsk_travisにどのパッケージをコンパイルするかの指示ができるようにする
4. jsk_pcl_rosとjsk_perceptionをjsk_recogntion_msgsを使う形に変更。テストもかえる
5. jsk_control, jsk_visualizationもjsk_recognition_msgsを使うように変更する

**Comment by garaemon** [comment]
* jsk_recognition_msgsを追加してrelease

**Comment by garaemon** [comment]
jsk_visualization is ready
* https://github.com/jsk-ros-pkg/jsk_visualization/pull/296
* https://github.com/jsk-ros-pkg/jsk_visualization/pull/295

**Comment by garaemon** [comment]
jsk_recognition is almost ready
* https://github.com/jsk-ros-pkg/jsk_recognition/pull/665

**Comment by garaemon** [comment]
jsk_control is almost ready
* https://github.com/jsk-ros-pkg/jsk_control/pull/205

**Comment by garaemon** [comment]
almost done

**Comment by garaemon** [comment]
a lot of work done!!
