### ISSUE TITLE
jenkins testing does not end within 50 minutes

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_recognition#715]
One solution is to use ccache with shareding cache by different docker containers.
https://github.com/jsk-ros-pkg/jsk_travis/issues/53

**Comment by garaemon** [comment]
@k-okada Can we use multiple processors on jenkins?

**Comment by garaemon** [comment]
I plan to change parallel option from `-p1` to `-p8` or something like that.

**Comment by garaemon** [comment]
Another solution is to separate jsk_pcl_ros into more smaller packages. for example, jsk_pcl_ros_util, jsk_pcl_ros_base, jsk_pcl_ros_core.

And jsk_pcl_ros depends on them. In testing phase, we can compile them separately

**Comment by k-okada** [comment]
> @k-okada Can we use multiple processors on jenkins?

I think so, using -p8 on jenkins is ncie to do.


--
◉ Kei Okada

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/716

**Comment by garaemon** [comment]
solved by using jenkins.jsk
