### ISSUE TITLE
ドアノブ認識でX軸が逆向きになることがある

### ISSUE THREAD

**Issue by mmurooka** [jsk-ros-pkg/jsk_recognition#727]
緊急ではないですが報告です．
ドアノブ認識の結果で，X軸がノブの長軸方向ですが，
この向きが同じドアを認識したときに逆になったりならなかったりします．

**Comment by k-okada** [comment]
全くのヤマカンですが，PCA使っているとこれは避けられないですね．受け取り側でロボットの視線との内積でも計算してv- しましょう．

--
◉ Kei Okada


2015-02-20 11:29 GMT+09:00 Masaki Murooka <notifications@github.com>:

**Comment by garaemon** [comment]
当たりです。認識側でも対応しますが、eus側で無理やりflipしておいてください

✉︎ Ryohei Ueda




On Thu, Feb 19, 2015 at 6:33 PM -0800, "Kei Okada" <notifications@github.com> wrote:










全くのヤマカンですが，PCA使っているとこれは避けられないですね．受け取り側でロボットの視線との内積でも計算してv- しましょう．





--


◉ Kei Okada








2015-02-20 11:29 GMT+09:00 Masaki Murooka <notifications@github.com>:

**Comment by mmurooka** [comment]
はい，現状はそのようにしています，ということで緊急ではないです．

**Comment by garaemon** [comment]
z軸の向きとかも逆な気がしていて、この辺は明日修正します

✉︎ Ryohei Ueda




On Thu, Feb 19, 2015 at 7:53 PM -0800, "Masaki Murooka" <notifications@github.com> wrote:












はい，現状はそのようにしています，ということで緊急ではないです．

**Comment by garaemon** [comment]
多分治っています
