### ISSUE TITLE
What is the best way to make color image from organized point cloud?

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_recognition#762]
I want to create color image generated from organized point cloud (using pass_throughed point cloud as input, so some parts are null. I hope that those invalid points become black in the color image).

I used depth_image_creator, but it was monochrome.

**Comment by garaemon** [comment]
We should use PointIndices and MaskImage.

1. generate PointIndices from organized pointcloud (You need to implement it)
2. convert PointIndices to MaskImage (jsk_pcl/PointIndicesToMaskImage)
3. apply mask image to the original image (jsk_perception/ApplyMaskImage)

**Comment by aginika** [comment]
@garaemon  Thanks a lot !!
I added to #765 which you suggest to implement.
And I realied to generate image.
Thanks.
