### ISSUE TITLE
[jsk_pcl_ros] Attention Clippers's crop PointCloud Indices including nan or inf points?

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_recognition#888]
When I use Attention Clipper with rosparam bounding box setting, 
the outpu/point_indices seems to count nan / infinite value.
I hope this clipper only count the pointcloud in the bounding box

In below image, left top is the pointclou_indices and there are many white points
![attention_clipper](https://cloud.githubusercontent.com/assets/3803922/7439394/d7b64434-f0b3-11e4-9d10-0b3e3b9f650d.png)

**Comment by aginika** [comment]
Thank you, I will try to use it.

**Comment by garaemon** [comment]
I havent confurmed it works, please check it

**Comment by aginika** [comment]
@garaemon I confirmed on baxter, Thanks. I fix a few parts in #891
