### ISSUE TITLE
Resize point cloud from Kinect2

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_recognition#907]
I tried to use OrganizedPassthrough and I can see the resized output in rviz, but the output topic has  1920 x 1080  according to `rostopic echo `'s width and hegiht ...(I expected 640 * 480 as I described in launch)
Can I really resize it?
Is it enough fast no matter whether I got really resized output or not?

**Comment by garaemon** [comment]
filtered points are represented as nan point to keep it organized

**Comment by aginika** [comment]
Is there any nodelet which can really trim the points and publish trimmed smaller points?(e.g. input: 1920x1080 -> outpu : 640 x480)

**Comment by garaemon** [comment]
Passthrough with keep organized false or add flag to unorder pointcloud to organized passthrough

**Comment by garaemon** [comment]
or apply crop_decimate to original depth image but i don't know it can handle float image

**Comment by aginika** [comment]
hmm,Thanks a lot, I will use the organized passthrough
