### ISSUE TITLE
[jsk_perception]   make_warped_images in point_pose_extractor 

### ISSUE THREAD

**Issue by h-kamada** [jsk-ros-pkg/jsk_recognition#919]
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/point_pose_extractor.cpp#L812-L817

見間違いなら申し訳ないのですが、この行によるfR3やfT3への変更がrvecやtvecなどに反映されていないように見えますが、反映されているのでしょうか？

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/point_pose_extractor.cpp#L807

これがあるから反映されているんじゃないかな?

**Comment by h-kamada** [comment]
すみません単純な勘違いをしていました。
