### ISSUE TITLE
Why the encoding of GridLabel's output image is 32SC1?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_recognition#950]

**Comment by garaemon** [comment]
Because the value means label index

**Comment by garaemon** [comment]
I know 8UC1 is better for this usage, you can change it.

**Comment by wkentaro** [comment]
Thanks.

**Comment by wkentaro** [comment]
I sent PR : https://github.com/jsk-ros-pkg/jsk_recognition/pull/951
