### ISSUE TITLE
cannot change number of particles in particle filter tracker

### ISSUE THREAD

**Issue by wesleypchan** [jsk-ros-pkg/jsk_recognition#986]
Tried setting the particle_num param to reduce the number of particles to speed up tracker, but in rviz it seems to still show a large number of particles.

After some initial debugging, it seems like the number of particles is getting set properly to particle_num initially, but after a few calls to cloud_cb it gets reverted back to 1000 for some reason.

**Comment by wesleypchan** [comment]
After more debugging, it seems like the line of code causing the problem is tracker_->compute().
After calling tracker_->compute(), the number of particles gets reverted to 1000.

**Comment by wesleypchan** [comment]
Seems like setting max_particle_num_ = particle_num solves the problem, but I'm not sure if this is the correct fix.

**Comment by garaemon** [comment]
particle_num is just an initial number of particles . The number of
particles changes

◉  ryohei

**Comment by wesleypchan** [comment]
so if I want to limit the number of particles to make the tracker run faster what would be the proper way of doing it?

**Comment by garaemon** [comment]
max_particle_num should work for the purpose

**Comment by wesleypchan** [comment]
changing max_particle_num worked
